import {
  CheckCheck,
  Clock3,
  History,
  Play,
  Redo2,
  Search,
  ShieldCheck,
  Undo2,
  Upload,
  ZoomIn,
} from "lucide-react";
import type { ToolAction, WorkflowBuilderData } from "./types";

export const toolbarActions: ToolAction[] = [
  { id: "undo", label: "Undo", icon: Undo2 },
  { id: "redo", label: "Redo", icon: Redo2 },
  { id: "zoom", label: "Zoom", icon: ZoomIn },
  { id: "minimap", label: "Mini Map", icon: Search },
  { id: "simulation", label: "Simulation", icon: Play },
  { id: "validate", label: "Validate", icon: CheckCheck },
  { id: "publish", label: "Publish", icon: Upload },
  { id: "versions", label: "Version History", icon: History },
];

export const workflowBuilderData: WorkflowBuilderData = {
  leftLibrary: [
    { id: "l1", label: "Workflow Builder", href: "/app/workflows", meta: "Current" },
    { id: "l2", label: "Command Center", href: "/app/commands", meta: "Workspace" },
    { id: "l3", label: "Agent Studio", href: "/app/agents", meta: "Workspace" },
  ],
  templates: [
    { id: "t1", label: "Executive Decision Flow", href: "#", meta: "Template" },
    { id: "t2", label: "Sales Escalation Workflow", href: "#", meta: "Template" },
    { id: "t3", label: "Compliance Validation", href: "#", meta: "Template" },
  ],
  favorites: [
    { id: "f1", label: "Board Briefing Runtime", href: "#", meta: "Published" },
    { id: "f2", label: "Revenue Protection Loop", href: "#", meta: "Draft" },
  ],
  recent: [
    { id: "r1", label: "Customer Churn Response", href: "#", meta: "10m ago" },
    { id: "r2", label: "Finance Forecast Approval", href: "#", meta: "27m ago" },
  ],
  categories: [
    { id: "c1", label: "Executive", href: "#", meta: "18" },
    { id: "c2", label: "Sales", href: "#", meta: "24" },
    { id: "c3", label: "Finance", href: "#", meta: "15" },
    { id: "c4", label: "Governance", href: "#", meta: "11" },
  ],
  teams: [
    { id: "tm1", label: "Leadership", href: "#", meta: "9 workflows" },
    { id: "tm2", label: "Revenue Ops", href: "#", meta: "14 workflows" },
    { id: "tm3", label: "Risk Council", href: "#", meta: "8 workflows" },
  ],
  nodePalette: [
    { type: "ai-agent", label: "AI Agent" },
    { type: "human-approval", label: "Human Approval" },
    { type: "business-rule", label: "Business Rule" },
    { type: "decision", label: "Decision Node" },
    { type: "knowledge-lookup", label: "Knowledge Lookup" },
    { type: "memory-retrieval", label: "Memory Retrieval" },
    { type: "policy", label: "Policy" },
    { type: "external-system", label: "External System" },
    { type: "mcp-tool", label: "MCP Tool" },
    { type: "notification", label: "Notification" },
    { type: "scheduler", label: "Scheduler" },
    { type: "condition", label: "Condition" },
    { type: "merge", label: "Merge" },
    { type: "split", label: "Split" },
    { type: "loop", label: "Loop" },
    { type: "report", label: "Report" },
  ],
  nodes: [
    {
      id: "n1",
      title: "Start Scheduler",
      type: "scheduler",
      description: "Daily executive orchestration trigger",
      x: 80,
      y: 120,
      status: "success",
      owner: "Operations",
    },
    {
      id: "n2",
      title: "Memory Retrieval",
      type: "memory-retrieval",
      description: "Load prior decisions and execution memory",
      x: 300,
      y: 120,
      status: "running",
      owner: "Knowledge",
    },
    {
      id: "n3",
      title: "Knowledge Lookup",
      type: "knowledge-lookup",
      description: "Fetch governance and sales knowledge context",
      x: 530,
      y: 120,
      status: "running",
      owner: "Knowledge",
    },
    {
      id: "n4",
      title: "Decision Intelligence",
      type: "decision",
      description: "Route business decision based on policy and impact",
      x: 760,
      y: 120,
      status: "attention",
      owner: "Executive Office",
      decisionType: "Strategic Allocation",
      businessImpact: "€2.4M revenue exposure",
      riskLevel: "Medium",
      policyApplied: "FIN-42",
      aiConfidence: 91,
      approvalRequired: true,
      deadline: "Today 17:30",
      executiveGoal: "Q3 Margin Protection",
      reasoningAvailable: true,
    },
    {
      id: "n5",
      title: "Human Approval",
      type: "human-approval",
      description: "CFO + COO approval gate",
      x: 990,
      y: 120,
      status: "idle",
      owner: "Leadership",
    },
    {
      id: "n6",
      title: "MCP Tool Execution",
      type: "mcp-tool",
      description: "Invoke workflow execution toolkit",
      x: 1220,
      y: 120,
      status: "idle",
      owner: "Platform",
    },
    {
      id: "n7",
      title: "Publish Report",
      type: "report",
      description: "Generate executive outcome report",
      x: 1450,
      y: 120,
      status: "idle",
      owner: "Executive Office",
    },
  ],
  edges: [
    { id: "e1", from: "n1", to: "n2", label: "trigger" },
    { id: "e2", from: "n2", to: "n3", label: "context" },
    { id: "e3", from: "n3", to: "n4", label: "evidence" },
    { id: "e4", from: "n4", to: "n5", label: "approval" },
    { id: "e5", from: "n5", to: "n6", label: "execute" },
    { id: "e6", from: "n6", to: "n7", label: "outcome" },
  ],
  intelligence: [
    { id: "i1", label: "Workflow Confidence", value: "93%", detail: "AI reasoning enabled" },
    { id: "i2", label: "Estimated Runtime", value: "08m 40s", detail: "Current branch" },
    { id: "i3", label: "Business Impact", value: "€2.4M", detail: "Revenue sensitivity" },
    { id: "i4", label: "Risk Score", value: "28", detail: "Managed risk band" },
    { id: "i5", label: "Organization Alignment", value: "97%", detail: "Executive objectives" },
    { id: "i6", label: "Knowledge Sources", value: "36", detail: "Connected" },
    { id: "i7", label: "Memory Collections", value: "145", detail: "Synchronized" },
    { id: "i8", label: "Connected MCP Tools", value: "18", detail: "Federated" },
    { id: "i9", label: "Human Approvals", value: "2", detail: "Pending" },
  ],
  simulation: [
    { id: "s1", label: "Execution Path", value: "Primary Decision Path", detail: "n1 -> n7" },
    { id: "s2", label: "Expected Runtime", value: "08m 40s", detail: "Simulation estimate" },
    { id: "s3", label: "Decision Branches", value: "3", detail: "YES / NO / Escalate" },
    { id: "s4", label: "Knowledge Retrieval", value: "12 queries", detail: "cached 7" },
    { id: "s5", label: "Memory Access", value: "24 pulls", detail: "policy + decisions" },
    { id: "s6", label: "Policy Validation", value: "11 checks", detail: "all pass" },
    { id: "s7", label: "External Systems", value: "4", detail: "Salesforce, SAP, M365, DWH" },
    { id: "s8", label: "Estimated Cost", value: "€186", detail: "runtime compute" },
    { id: "s9", label: "Simulation Confidence", value: "92%", detail: "historical variance" },
  ],
  optimization: [
    { id: "o1", title: "Merge duplicated approvals", impact: "Remove 1 approval step" },
    { id: "o2", title: "Replace manual review with AI Agent", impact: "Reduce runtime by 22%" },
    { id: "o3", title: "Cache repeated knowledge lookup", impact: "Reduce latency by 31%" },
    { id: "o4", title: "Reuse Finance Agent", impact: "Increase confidence +4%" },
    { id: "o5", title: "Optimize execution path", impact: "Reduce runtime by 32%" },
    { id: "o6", title: "Reuse existing workflow", impact: "Faster rollout by 2 days" },
  ],
  organizationContext: [
    { id: "oc1", label: "Executive" },
    { id: "oc2", label: "Sales" },
    { id: "oc3", label: "Marketing" },
    { id: "oc4", label: "Finance" },
    { id: "oc5", label: "Legal" },
    { id: "oc6", label: "Operations" },
    { id: "oc7", label: "HR" },
    { id: "oc8", label: "Customer Success" },
    { id: "oc9", label: "Microsoft 365" },
    { id: "oc10", label: "Salesforce" },
    { id: "oc11", label: "SAP" },
    { id: "oc12", label: "MCP Connected" },
    { id: "oc13", label: "Organization Graph" },
    { id: "oc14", label: "Runtime Events" },
    { id: "oc15", label: "Executive Memory" },
    { id: "oc16", label: "Knowledge Graph" },
  ],
  decisionIntelligence: [
    { id: "d1", label: "Decision Owner", value: "CFO", detail: "Executive committee" },
    { id: "d2", label: "Decision Type", value: "Strategic Allocation", detail: "Capital decision" },
    { id: "d3", label: "Business Impact", value: "€2.4M", detail: "Revenue protection" },
    { id: "d4", label: "Risk Level", value: "Medium", detail: "Policy managed" },
    { id: "d5", label: "Policy Applied", value: "FIN-42", detail: "Governance policy" },
    { id: "d6", label: "AI Confidence", value: "91%", detail: "Reasoning complete" },
    { id: "d7", label: "Human Approval Required", value: "Yes", detail: "2 approvers" },
    { id: "d8", label: "Decision Deadline", value: "Today 17:30", detail: "SLA on track" },
    { id: "d9", label: "Executive Goal", value: "Q3 Margin Protection", detail: "Top priority" },
    { id: "d10", label: "Reasoning Available", value: "Yes", detail: "Traceable" },
  ],
  businessOutcomes: [
    { id: "bo1", label: "Estimated Revenue Impact", value: "€1.8M", detail: "Upside" },
    { id: "bo2", label: "Estimated Cost Reduction", value: "€320k", detail: "Annualized" },
    { id: "bo3", label: "Risk Reduction", value: "27%", detail: "Policy reinforced" },
    { id: "bo4", label: "Time Saved", value: "41h / month", detail: "Automation" },
    { id: "bo5", label: "Executive Priority Alignment", value: "97%", detail: "Strategic fit" },
    { id: "bo6", label: "Compliance Improvement", value: "14%", detail: "Control quality" },
    { id: "bo7", label: "Organization Health", value: "95", detail: "Composite index" },
    { id: "bo8", label: "Customer Impact", value: "+9 NPS", detail: "Predicted" },
  ],
  analytics: [
    { id: "a1", label: "Execution Success", value: "98.4%", detail: "Last 30d" },
    { id: "a2", label: "Average Runtime", value: "07m 58s", detail: "Per run" },
    { id: "a3", label: "Approval Time", value: "01m 12s", detail: "Median" },
    { id: "a4", label: "Runtime Availability", value: "99.97%", detail: "Platform" },
    { id: "a5", label: "AI Confidence", value: "92%", detail: "Aggregated" },
    { id: "a6", label: "Policy Compliance", value: "99.2%", detail: "All checks" },
    { id: "a7", label: "Knowledge Freshness", value: "96%", detail: "Source health" },
    { id: "a8", label: "Memory Health", value: "95%", detail: "Collection quality" },
  ],
  recentExecutions: [
    { id: "re1", title: "Workflow Started", description: "Daily orchestration run initiated", time: "09:11" },
    { id: "re2", title: "Knowledge Retrieved", description: "12 sources queried and merged", time: "09:12" },
    { id: "re3", title: "Memory Updated", description: "Decision memory collection appended", time: "09:13" },
    { id: "re4", title: "Decision Generated", description: "Strategic allocation recommendation prepared", time: "09:14" },
    { id: "re5", title: "Human Approved", description: "CFO approval captured", time: "09:16" },
    { id: "re6", title: "Policy Validated", description: "FIN-42 and GOV-18 checks passed", time: "09:17" },
    { id: "re7", title: "Workflow Published", description: "Version v1.2 promoted", time: "09:18" },
    { id: "re8", title: "Report Generated", description: "Executive summary distributed", time: "09:19" },
  ],
  inspectorInputs: [
    { id: "in1", label: "Pipeline risk dataset", href: "#", meta: "live" },
    { id: "in2", label: "Budget variance feed", href: "#", meta: "hourly" },
  ],
  inspectorOutputs: [
    { id: "out1", label: "Executive recommendation", href: "#", meta: "priority" },
    { id: "out2", label: "Approval request packet", href: "#", meta: "governed" },
  ],
  permissions: [
    { id: "perm1", label: "Read: Finance models", href: "#", meta: "allowed" },
    { id: "perm2", label: "Write: Decision log", href: "#", meta: "allowed" },
  ],
  knowledgeSources: [
    { id: "k1", label: "Board policy handbook", href: "#", meta: "fresh" },
    { id: "k2", label: "Sales forecast playbook", href: "#", meta: "fresh" },
  ],
  memoryCollections: [
    { id: "m1", label: "Executive memory stream", href: "#", meta: "145 items" },
    { id: "m2", label: "Risk event memory", href: "#", meta: "92 items" },
  ],
  policies: [
    { id: "p1", label: "FIN-42 Capital Allocation", href: "#", meta: "enforced" },
    { id: "p2", label: "GOV-18 Approval Chain", href: "#", meta: "enforced" },
  ],
  runtimeSettings: [
    { id: "rs1", label: "Max retries: 3", href: "#", meta: "stable" },
    { id: "rs2", label: "Timeout: 120s", href: "#", meta: "stable" },
  ],
  connectedMcpTools: [
    { id: "mt1", label: "MCP Policy Engine", href: "#", meta: "connected" },
    { id: "mt2", label: "MCP Knowledge Gateway", href: "#", meta: "connected" },
  ],
  executionHistory: [
    { id: "eh1", title: "v1.1 executed", description: "Completed with approval latency 74s", time: "Yesterday" },
    { id: "eh2", title: "v1.2 dry-run", description: "Simulation confidence 92%", time: "Today 08:40" },
  ],
  suggestedImprovements: [
    { id: "si1", label: "Remove duplicate approval branch", href: "#", meta: "high" },
    { id: "si2", label: "Cache knowledge lookup step", href: "#", meta: "medium" },
  ],
};

export const primaryHeaderActions: ToolAction[] = [
  { id: "new", label: "New Workflow", icon: Play },
  { id: "import", label: "Import", icon: Upload },
  { id: "templates", label: "Templates", icon: Search },
  { id: "publish", label: "Publish", icon: ShieldCheck },
  { id: "history", label: "Version History", icon: Clock3 },
];
