import type {
  ApprovalStep,
  DecisionFilter,
  DecisionGraphEdge,
  DecisionGraphNode,
  DecisionInsight,
  DecisionMetrics,
  DecisionRecord,
  DecisionRibbonItem,
  DecisionRoleView,
  DecisionScenario,
  DecisionSidebarSection,
  DecisionTimelineEvent,
  RoleIntelligenceItem,
} from "./types";

export const decisionMetrics: DecisionMetrics = [
  { id: "m1", label: "Pending Decisions", value: "42", detail: "Executive queue" },
  { id: "m2", label: "AI Recommendations", value: "118", detail: "Ready for review" },
  { id: "m3", label: "Average Confidence", value: "94%", detail: "Decision model confidence" },
  { id: "m4", label: "Estimated Business Impact", value: "€12.8M", detail: "Quarterly impact" },
  { id: "m5", label: "Automation Rate", value: "61%", detail: "Autonomous execution" },
  { id: "m6", label: "Approval SLA", value: "7.2h", detail: "Median approval time" },
  { id: "m7", label: "Escalations", value: "6", detail: "Executive escalations" },
  { id: "m8", label: "Risk Index", value: "18", detail: "Composite risk signal" },
];

export const decisionRibbonItems: DecisionRibbonItem[] = [
  { id: "r1", label: "Pending Executive Decisions", value: "42", status: "Queue active", trend: "+3", tone: "warning" },
  { id: "r2", label: "High Risk Decisions", value: "9", status: "Monitor", trend: "-1", tone: "critical" },
  { id: "r3", label: "Automation Opportunities", value: "27", status: "Eligible", trend: "+4", tone: "success" },
  { id: "r4", label: "Waiting for Approval", value: "14", status: "Pending", trend: "+1", tone: "warning" },
  { id: "r5", label: "Human Review Required", value: "11", status: "Manual review", trend: "-2", tone: "default" },
  { id: "r6", label: "Average Confidence", value: "94%", status: "Stable", trend: "+0.6%", tone: "success" },
  { id: "r7", label: "Estimated Revenue Impact", value: "€4.6M", status: "Monthly run-rate", trend: "+8.3%", tone: "success" },
  { id: "r8", label: "Average Processing Time", value: "6.8h", status: "Decision cycle", trend: "-0.9h", tone: "success" },
];

export const decisionFilters: DecisionFilter[] = [
  { id: "department", label: "Department" },
  { id: "impact", label: "Business Impact" },
  { id: "risk", label: "Risk Level" },
  { id: "urgency", label: "Urgency" },
  { id: "compliance", label: "Compliance" },
  { id: "owner", label: "Owner" },
  { id: "status", label: "Approval Status" },
  { id: "date", label: "Date" },
];

export const decisionSidebarSections: DecisionSidebarSection[] = [
  {
    title: "Decision Inbox",
    items: [
      { id: "pending", label: "Pending", href: "#", meta: "42" },
      { id: "recommended", label: "Recommended", href: "#", meta: "118" },
      { id: "approved", label: "Approved", href: "#", meta: "367" },
      { id: "rejected", label: "Rejected", href: "#", meta: "29" },
      { id: "high-risk", label: "High Risk", href: "#", meta: "9" },
    ],
  },
  {
    title: "Decision Classes",
    items: [
      { id: "strategic", label: "Strategic", href: "#", meta: "15" },
      { id: "operational", label: "Operational", href: "#", meta: "31" },
      { id: "financial", label: "Financial", href: "#", meta: "22" },
      { id: "compliance", label: "Compliance", href: "#", meta: "17" },
      { id: "security", label: "Security", href: "#", meta: "8" },
      { id: "customer", label: "Customer", href: "#", meta: "19" },
      { id: "hr", label: "HR", href: "#", meta: "6" },
      { id: "archived", label: "Archived", href: "#", meta: "124" },
    ],
  },
];

export const decisionRecords: DecisionRecord[] = [
  {
    id: "d1",
    title: "Approve Warehouse Expansion - Midwest Region",
    executiveSummary: "Demand growth requires a new fulfillment node to protect delivery SLA and reduce shipping cost.",
    recommendation: "Approve phased warehouse expansion in Q4 with staged automation rollout.",
    aiRecommendation: "Approve with staged capex release and monthly utilization checkpoints.",
    reasoning: "Order velocity and distribution cost trends indicate capacity constraints in the current network.",
    supportingEvidence: [
      "Delivery SLA breach risk reaches 17% in peak month simulation",
      "Transportation cost projected to rise 12.4% without expansion",
      "Automation readiness in target site scored 93%",
    ],
    signals: ["Order growth +18%", "SLA risk alert", "Cost pressure in central logistics"],
    dependencies: ["Capital approval", "Vendor onboarding", "Workforce plan"],
    tradeoffs: ["Higher short-term capex", "Reduced long-term shipping cost", "Improved customer retention"],
    alternatives: ["Delay 2 quarters", "Outsource overflow", "Expand current site only"],
    confidence: 96,
    businessImpact: "Improves delivery reliability for enterprise accounts",
    financialImpact: "Projected annual net benefit: €3.2M",
    risk: "medium",
    urgency: "high",
    strategicAlignment: 95,
    timeSensitivity: 88,
    affectedDepartments: ["Operations", "Finance", "Sales"],
    linkedMemory: ["Q2 logistics postmortem", "Enterprise retention risk review"],
    linkedKnowledge: ["Distribution policy", "Fulfillment expansion standard"],
    linkedWorkflow: ["Capital expenditure workflow", "Vendor compliance workflow"],
    linkedAgent: ["Operations Planner", "Finance Analyst"],
    estimatedROI: "21 months payback",
    approvalStatus: "recommended",
    category: "strategic",
    compliance: "Compliant with expansion governance",
    stakeholders: ["COO", "CFO", "Head of Operations"],
    createdAt: "2026-07-09T09:30:00Z",
    updatedAt: "2026-07-10T08:35:00Z",
  },
  {
    id: "d2",
    title: "Delay European Rollout - Q1",
    executiveSummary: "Operational and legal readiness gaps create high execution risk for immediate launch.",
    recommendation: "Delay rollout by one quarter and complete compliance and localization milestones.",
    aiRecommendation: "Delay and re-sequence to protect margin and customer trust.",
    reasoning: "Current compliance and support readiness remain below launch threshold.",
    supportingEvidence: [
      "Localization coverage at 71%",
      "Regulatory documentation missing for 3 target countries",
      "Projected launch churn risk +9% if unchanged",
    ],
    signals: ["Compliance readiness alert", "Localization backlog", "Support capacity shortfall"],
    dependencies: ["Legal sign-off", "Customer support hiring", "Localized billing integration"],
    tradeoffs: ["Delayed revenue recognition", "Lower launch risk", "Higher first-quarter conversion quality"],
    alternatives: ["Launch in one country", "Partial feature rollout"],
    confidence: 93,
    businessImpact: "Preserves launch quality and protects brand in new markets",
    financialImpact: "Avoids estimated €1.1M rework and churn-related loss",
    risk: "high",
    urgency: "medium",
    strategicAlignment: 87,
    timeSensitivity: 72,
    affectedDepartments: ["Legal", "Operations", "Customer Success"],
    linkedMemory: ["EMEA rollout retrospective", "Support readiness assessment"],
    linkedKnowledge: ["International launch policy", "Localization standard"],
    linkedWorkflow: ["Market launch workflow", "Compliance approval workflow"],
    linkedAgent: ["Compliance Officer", "Launch Strategist"],
    estimatedROI: "Risk avoidance over 2 quarters",
    approvalStatus: "pending",
    category: "compliance",
    compliance: "Requires additional legal review",
    stakeholders: ["CEO", "General Counsel", "COO"],
    createdAt: "2026-07-08T11:10:00Z",
    updatedAt: "2026-07-10T07:50:00Z",
  },
  {
    id: "d3",
    title: "Increase Customer Support Agents - Enterprise Tier",
    executiveSummary: "Ticket complexity and SLA risk indicate capacity constraints for top-tier accounts.",
    recommendation: "Approve incremental hiring with AI-assisted routing automation.",
    aiRecommendation: "Approve 12 FTEs and enable support copilot workflows.",
    reasoning: "Queue analysis shows high-value accounts are approaching SLA breach thresholds.",
    supportingEvidence: [
      "Enterprise ticket backlog +23%",
      "Escalation rate rose from 4.1% to 6.3%",
      "Copilot-assisted resolution improves speed by 19%",
    ],
    signals: ["Ticket backlog alert", "Escalation increase", "CSAT dip"],
    dependencies: ["Hiring budget", "Training plan", "Tooling enablement"],
    tradeoffs: ["Increased payroll", "Higher retention", "Improved expansion revenue"],
    alternatives: ["Outsource overflow", "Shift-only reallocation"],
    confidence: 94,
    businessImpact: "Protects retention and expansion for enterprise segment",
    financialImpact: "Projected annual net gain: €2.1M",
    risk: "medium",
    urgency: "high",
    strategicAlignment: 92,
    timeSensitivity: 84,
    affectedDepartments: ["Customer Success", "HR", "Finance"],
    linkedMemory: ["Enterprise support trend analysis"],
    linkedKnowledge: ["Support coverage policy", "Hiring standard"],
    linkedWorkflow: ["Headcount approval workflow"],
    linkedAgent: ["Customer Success Agent", "HR Planner"],
    estimatedROI: "15 months payback",
    approvalStatus: "recommended",
    category: "customer",
    compliance: "Compliant",
    stakeholders: ["COO", "CHRO", "CFO"],
    createdAt: "2026-07-09T13:20:00Z",
    updatedAt: "2026-07-10T08:22:00Z",
  },
  {
    id: "d4",
    title: "Merge Duplicate Workflows in Procurement",
    executiveSummary: "Redundant workflows create approval delays and control inconsistencies.",
    recommendation: "Merge duplicate procurement workflows into one governed approval path.",
    aiRecommendation: "Approve consolidation and retire legacy branch.",
    reasoning: "Workflow telemetry indicates parallel steps duplicate control checks and increase cycle time.",
    supportingEvidence: [
      "Cycle time increased 28% over quarter",
      "Duplicate review step identified in 82% of requests",
      "Control coverage remains equivalent after merge simulation",
    ],
    signals: ["Workflow variance alert", "Approval delay trend"],
    dependencies: ["Workflow migration", "Policy update", "Stakeholder training"],
    tradeoffs: ["Change management effort", "Improved throughput", "Lower governance drift"],
    alternatives: ["Keep both paths with stricter routing"],
    confidence: 91,
    businessImpact: "Improves procurement speed and consistency",
    financialImpact: "Estimated annual productivity gain: €640K",
    risk: "low",
    urgency: "medium",
    strategicAlignment: 89,
    timeSensitivity: 63,
    affectedDepartments: ["Operations", "Finance", "Compliance"],
    linkedMemory: ["Procurement delay review"],
    linkedKnowledge: ["Procurement policy", "Workflow design standard"],
    linkedWorkflow: ["Procurement approval workflow"],
    linkedAgent: ["Workflow Optimizer"],
    estimatedROI: "9 months payback",
    approvalStatus: "pending",
    category: "operational",
    compliance: "Requires policy reference update",
    stakeholders: ["COO", "Compliance Lead"],
    createdAt: "2026-07-08T16:00:00Z",
    updatedAt: "2026-07-10T06:58:00Z",
  },
  {
    id: "d5",
    title: "Approve AI Onboarding Program",
    executiveSummary: "A structured AI onboarding program is needed to improve adoption quality and governance.",
    recommendation: "Approve enterprise AI onboarding with role-based tracks and policy certification.",
    aiRecommendation: "Approve and launch in two phases with governance checkpoints.",
    reasoning: "Current adoption is uneven and increases policy exception risk.",
    supportingEvidence: [
      "AI feature adoption varies from 34% to 82% across departments",
      "Policy exceptions concentrated in low-training teams",
      "Projected productivity improvement +11% with onboarding",
    ],
    signals: ["Adoption variance", "Policy exception trend", "Training demand signal"],
    dependencies: ["Learning content", "Manager enablement", "Policy certification flow"],
    tradeoffs: ["Program cost", "Higher quality adoption", "Lower compliance risk"],
    alternatives: ["Self-service only", "Department-led rollout"],
    confidence: 92,
    businessImpact: "Improves enterprise AI consistency and decision quality",
    financialImpact: "Estimated annual value: €1.7M",
    risk: "medium",
    urgency: "medium",
    strategicAlignment: 94,
    timeSensitivity: 70,
    affectedDepartments: ["HR", "IT", "Compliance"],
    linkedMemory: ["AI adoption report", "Exception review notes"],
    linkedKnowledge: ["AI governance framework", "Learning standards"],
    linkedWorkflow: ["Training certification workflow"],
    linkedAgent: ["AI Assistant", "Compliance Officer"],
    estimatedROI: "12 months payback",
    approvalStatus: "review",
    category: "hr",
    compliance: "Compliant",
    stakeholders: ["CHRO", "CIO", "Compliance Lead"],
    createdAt: "2026-07-09T10:45:00Z",
    updatedAt: "2026-07-10T07:12:00Z",
  },
  {
    id: "d6",
    title: "Reduce Cloud Costs via Reserved Capacity",
    executiveSummary: "Usage patterns support reserved purchasing to reduce infrastructure spend.",
    recommendation: "Approve reserved capacity strategy with monthly optimization review.",
    aiRecommendation: "Approve 60% baseline reservation and dynamic overflow policy.",
    reasoning: "Workload consistency and forecast confidence meet reservation threshold.",
    supportingEvidence: [
      "Steady baseline utilization over 6 months",
      "Projected cost reduction 14.2%",
      "Operational risk remains within tolerance",
    ],
    signals: ["Cloud spend alert", "Forecast stability", "Optimization signal"],
    dependencies: ["Finance approval", "Procurement contract", "Cost monitoring"],
    tradeoffs: ["Reduced flexibility", "Lower cost", "Improved budget predictability"],
    alternatives: ["Spot only", "Partial reserved mix"],
    confidence: 95,
    businessImpact: "Lowers run-rate infrastructure cost",
    financialImpact: "Projected annual savings: €2.4M",
    risk: "low",
    urgency: "high",
    strategicAlignment: 90,
    timeSensitivity: 80,
    affectedDepartments: ["IT", "Finance", "Engineering"],
    linkedMemory: ["Cloud spend trend memory"],
    linkedKnowledge: ["Infrastructure cost policy"],
    linkedWorkflow: ["Infrastructure approval workflow"],
    linkedAgent: ["Infrastructure Optimizer"],
    estimatedROI: "6 months payback",
    approvalStatus: "recommended",
    category: "financial",
    compliance: "Compliant",
    stakeholders: ["CFO", "CIO", "Head of Engineering"],
    createdAt: "2026-07-09T15:05:00Z",
    updatedAt: "2026-07-10T08:00:00Z",
  },
  {
    id: "d7",
    title: "Launch Enterprise Pricing 2.0",
    executiveSummary: "Updated pricing model improves expansion path and margin performance.",
    recommendation: "Approve phased pricing rollout with customer impact safeguards.",
    aiRecommendation: "Approve with strategic account guardrails and migration playbook.",
    reasoning: "Simulation indicates margin uplift with manageable retention impact.",
    supportingEvidence: [
      "Gross margin projected +4.8 points",
      "Renewal sensitivity manageable with guardrails",
      "Sales enablement readiness at 89%",
    ],
    signals: ["Margin optimization signal", "Pricing scenario output", "Retention guardrail alerts"],
    dependencies: ["Sales enablement", "Contract migration process", "Customer communication"],
    tradeoffs: ["Potential short-term friction", "Higher margin", "Better package clarity"],
    alternatives: ["Delay to next fiscal year", "Pilot in one segment"],
    confidence: 90,
    businessImpact: "Improves enterprise margin while preserving strategic accounts",
    financialImpact: "Projected annual margin impact: €5.1M",
    risk: "high",
    urgency: "high",
    strategicAlignment: 96,
    timeSensitivity: 86,
    affectedDepartments: ["Sales", "Finance", "Customer Success"],
    linkedMemory: ["Pricing retrospective", "Enterprise renewal cohort notes"],
    linkedKnowledge: ["Pricing policy", "Contract migration standard"],
    linkedWorkflow: ["Pricing approval workflow", "Customer communication workflow"],
    linkedAgent: ["Revenue Strategist", "Customer Risk Agent"],
    estimatedROI: "10 months payback",
    approvalStatus: "pending",
    category: "strategic",
    compliance: "Requires pricing committee sign-off",
    stakeholders: ["CEO", "CFO", "CRO"],
    createdAt: "2026-07-10T06:20:00Z",
    updatedAt: "2026-07-10T08:41:00Z",
  },
];

export const decisionGraphNodes: DecisionGraphNode[] = [
  { id: "d1", label: "Decision", type: "decision", x: 280, y: 250, radius: 26 },
  { id: "g1", label: "Memory", type: "memory", x: 120, y: 120, radius: 20 },
  { id: "g2", label: "Knowledge", type: "knowledge", x: 120, y: 380, radius: 20 },
  { id: "g3", label: "Workflow", type: "workflow", x: 460, y: 110, radius: 20 },
  { id: "g4", label: "Agent", type: "agent", x: 500, y: 360, radius: 20 },
  { id: "g5", label: "Department", type: "department", x: 680, y: 140, radius: 20 },
  { id: "g6", label: "Policy", type: "policy", x: 680, y: 360, radius: 20 },
  { id: "g7", label: "Goal", type: "goal", x: 860, y: 190, radius: 20 },
  { id: "g8", label: "Executive", type: "executive", x: 860, y: 330, radius: 20 },
  { id: "g9", label: "Risk", type: "risk", x: 1030, y: 260, radius: 20 },
];

export const decisionGraphEdges: DecisionGraphEdge[] = [
  { id: "e1", from: "g1", to: "d1", label: "context", animated: true },
  { id: "e2", from: "g2", to: "d1", label: "knowledge", animated: true },
  { id: "e3", from: "g3", to: "d1", label: "workflow", animated: true },
  { id: "e4", from: "g4", to: "d1", label: "agent", animated: true },
  { id: "e5", from: "d1", to: "g5", label: "impacts", animated: true },
  { id: "e6", from: "d1", to: "g6", label: "governed by", animated: true },
  { id: "e7", from: "d1", to: "g7", label: "aligned to", animated: true },
  { id: "e8", from: "d1", to: "g8", label: "approved by", animated: true },
  { id: "e9", from: "d1", to: "g9", label: "risk", animated: true },
];

export const decisionTimeline: DecisionTimelineEvent[] = [
  { id: "t1", stage: "created", title: "Decision created", detail: "Warehouse expansion scenario created by Operations Planner", timestamp: "2026-07-09T09:30:00Z" },
  { id: "t2", stage: "reviewed", title: "Reviewed by finance", detail: "Financial impact assumptions validated with Finance Analyst", timestamp: "2026-07-09T11:40:00Z" },
  { id: "t3", stage: "recommended", title: "AI recommendation issued", detail: "AI model recommended phased approval with checkpoints", timestamp: "2026-07-09T13:10:00Z" },
  { id: "t4", stage: "approved", title: "Executive pre-approval", detail: "COO marked proposal as ready for final review", timestamp: "2026-07-09T17:20:00Z" },
  { id: "t5", stage: "executed", title: "Execution staged", detail: "Initial vendor and site assessment workflow initiated", timestamp: "2026-07-10T06:35:00Z" },
  { id: "t6", stage: "measured", title: "Impact measured", detail: "Simulation predicts 5.4-point SLA improvement", timestamp: "2026-07-10T08:05:00Z" },
];

export const decisionInsights: DecisionInsight[] = [
  { id: "i1", title: "Approve warehouse expansion", detail: "Network pressure and retention risk indicate immediate value.", confidence: 96, impact: "€3.2M net annual benefit" },
  { id: "i2", title: "Delay European rollout", detail: "Compliance readiness gaps increase launch execution risk.", confidence: 93, impact: "Avoids €1.1M downside" },
  { id: "i3", title: "Increase customer support agents", detail: "SLA risk in enterprise tier requires capacity adjustment.", confidence: 94, impact: "€2.1M annual value" },
  { id: "i4", title: "Merge duplicate workflows", detail: "Consolidation reduces approval cycle time by 28%.", confidence: 91, impact: "€640K productivity gain" },
  { id: "i5", title: "Approve AI onboarding", detail: "Governed onboarding improves adoption quality and compliance.", confidence: 92, impact: "€1.7M annual value" },
  { id: "i6", title: "Reduce cloud costs", detail: "Reserved capacity plan offers lower run-rate with manageable risk.", confidence: 95, impact: "€2.4M savings" },
  { id: "i7", title: "Launch enterprise pricing", detail: "Revised model improves margin with strategic safeguards.", confidence: 90, impact: "€5.1M margin impact" },
];

export const decisionScenarios: DecisionScenario[] = [
  { id: "s1", label: "Approve", revenue: "+€3.2M", cost: "-€1.1M", risk: "Medium", customerSatisfaction: "+6.2", operationalEfficiency: "+12%", strategicAlignment: "95%" },
  { id: "s2", label: "Reject", revenue: "-€1.7M", cost: "+€0.4M", risk: "High", customerSatisfaction: "-4.1", operationalEfficiency: "-8%", strategicAlignment: "38%" },
  { id: "s3", label: "Delay", revenue: "+€0.8M", cost: "-€0.5M", risk: "Medium", customerSatisfaction: "+1.9", operationalEfficiency: "+3%", strategicAlignment: "71%" },
  { id: "s4", label: "Delegate", revenue: "+€1.4M", cost: "-€0.7M", risk: "Medium", customerSatisfaction: "+2.7", operationalEfficiency: "+7%", strategicAlignment: "79%" },
  { id: "s5", label: "Automate", revenue: "+€2.6M", cost: "-€0.9M", risk: "Low", customerSatisfaction: "+5.4", operationalEfficiency: "+16%", strategicAlignment: "91%" },
];

export const businessImpactMetrics: DecisionMetrics = [
  { id: "b1", label: "Revenue", value: "€9.8M", detail: "Projected annual uplift" },
  { id: "b2", label: "Savings", value: "€3.1M", detail: "Operational savings" },
  { id: "b3", label: "Efficiency", value: "+14%", detail: "Cycle-time improvement" },
  { id: "b4", label: "Compliance", value: "99.2%", detail: "Policy adherence" },
  { id: "b5", label: "Customer Experience", value: "+5.8", detail: "NPS impact" },
  { id: "b6", label: "Risk Reduction", value: "-27%", detail: "Critical risk exposure" },
  { id: "b7", label: "Strategic Value", value: "96", detail: "Executive alignment score" },
];

export const approvalFlow: ApprovalStep[] = [
  { id: "a1", label: "AI Recommendation", owner: "Decision Engine", status: "completed" },
  { id: "a2", label: "Department Review", owner: "Operations", status: "completed" },
  { id: "a3", label: "Financial Validation", owner: "Finance", status: "in-progress" },
  { id: "a4", label: "Executive Approval", owner: "COO", status: "waiting" },
];

export const roleViews: DecisionRoleView[] = ["CEO", "CFO", "COO", "HR", "Sales", "IT", "Compliance"];

export const roleIntelligence: RoleIntelligenceItem[] = [
  { id: "r-ceo", role: "CEO", priorities: ["Strategic growth", "Enterprise risk posture", "Decision velocity"], focusMetrics: ["Strategic Alignment", "Estimated Business Impact", "Risk Index"] },
  { id: "r-cfo", role: "CFO", priorities: ["Margin expansion", "Capital efficiency", "Cost governance"], focusMetrics: ["Financial Impact", "Estimated ROI", "Savings"] },
  { id: "r-coo", role: "COO", priorities: ["Operational throughput", "SLA integrity", "Execution reliability"], focusMetrics: ["Processing Time", "Automation Rate", "Operational Efficiency"] },
  { id: "r-hr", role: "HR", priorities: ["Workforce readiness", "Policy adoption", "Capability development"], focusMetrics: ["Approval SLA", "Compliance", "AI Onboarding"] },
  { id: "r-sales", role: "Sales", priorities: ["Revenue acceleration", "Renewal quality", "Pricing outcomes"], focusMetrics: ["Revenue", "Customer Experience", "Strategic Value"] },
  { id: "r-it", role: "IT", priorities: ["Infrastructure resilience", "Automation safety", "Security controls"], focusMetrics: ["Risk Reduction", "Automation Rate", "Compliance"] },
  { id: "r-compliance", role: "Compliance", priorities: ["Policy adherence", "Audit traceability", "Governance quality"], focusMetrics: ["Compliance", "Risk Index", "Approval Flow"] },
];
