import type { MemoryCollection, MemoryGraphLink, MemoryGraphNode, MemoryInsight, MemoryMetric, MemoryRecord, MemoryTimelineEvent, MemoryContextItem, MemoryFilter, SavedSearch } from "./types";

export const memoryMetrics: MemoryMetric[] = [
  { id: "m1", label: "Total Memories", value: "12,480", detail: "Across all collections" },
  { id: "m2", label: "Memory Health", value: "96%", detail: "Governed and current" },
  { id: "m3", label: "Knowledge Coverage", value: "94%", detail: "Enterprise sources linked" },
  { id: "m4", label: "Freshness Score", value: "91%", detail: "Updated within 24h" },
  { id: "m5", label: "Retrieval Accuracy", value: "98.2%", detail: "Validated samples" },
  { id: "m6", label: "Memory Growth", value: "+18%", detail: "Month over month" },
  { id: "m7", label: "Collections", value: "145", detail: "Managed collections" },
  { id: "m8", label: "Org Intelligence Score", value: "97", detail: "Composite index" },
  { id: "m9", label: "AI Confidence", value: "95%", detail: "Reasoning ready" },
];

export const memoryCollections: MemoryCollection[] = [
  { id: "c1", title: "Executive Board", count: 84, detail: "Board notes, decisions and strategic context", updatedAt: "2026-07-10T08:14:00Z" },
  { id: "c2", title: "Finance", count: 126, detail: "Forecasts, budget decisions and variance memory", updatedAt: "2026-07-10T07:56:00Z" },
  { id: "c3", title: "Sales", count: 191, detail: "Pipeline events, churn signals and account context", updatedAt: "2026-07-10T08:02:00Z" },
  { id: "c4", title: "Marketing", count: 104, detail: "Campaign insights and audience learnings", updatedAt: "2026-07-10T07:29:00Z" },
  { id: "c5", title: "Legal", count: 68, detail: "Policy approvals and compliance memory", updatedAt: "2026-07-10T08:40:00Z" },
  { id: "c6", title: "Operations", count: 143, detail: "Execution logs and process improvements", updatedAt: "2026-07-10T08:22:00Z" },
  { id: "c7", title: "HR", count: 56, detail: "People changes and organizational memory", updatedAt: "2026-07-09T18:12:00Z" },
  { id: "c8", title: "Engineering", count: 88, detail: "Product delivery and platform learnings", updatedAt: "2026-07-10T06:58:00Z" },
  { id: "c9", title: "Customer Success", count: 117, detail: "Renewal risk, health and service memory", updatedAt: "2026-07-10T08:18:00Z" },
  { id: "c10", title: "AI Agents", count: 212, detail: "Agent decisions, tool usage and outcomes", updatedAt: "2026-07-10T08:31:00Z" },
];

export const memoryRecords: MemoryRecord[] = [
  {
    id: "r1",
    title: "Q3 Executive Planning Session",
    summary: "Captured margin priorities, revenue risks and approval boundaries for the board narrative.",
    owner: "Chief Executive Officer",
    department: "Executive",
    type: "meeting",
    confidence: 97,
    importance: 98,
    tags: ["board", "q3", "margin", "strategy"],
    relationships: ["Q3 Margin Plan", "Finance Forecast v8", "Board Calendar"],
    retention: "Permanent",
    updatedAt: "2026-07-10T08:16:00Z",
    aiSummary: "High-value executive memory with strong downstream decision relevance.",
    permissions: "Executive, Finance, Governance",
    selected: true,
  },
  {
    id: "r2",
    title: "Enterprise Renewal Risk Pattern",
    summary: "Recurring drop in executive touchpoints correlated with renewal slippage in enterprise accounts.",
    owner: "Customer Success",
    department: "Customer Success",
    type: "customer",
    confidence: 94,
    importance: 95,
    tags: ["renewal", "risk", "customer", "retention"],
    relationships: ["Top 20 At-Risk Accounts", "Sales Playbook", "Churn Workflow"],
    retention: "24 months",
    updatedAt: "2026-07-10T07:41:00Z",
    aiSummary: "Pattern suggests leadership visibility should be added to retention workflows.",
    permissions: "Customer Success, Sales, Executive",
  },
  {
    id: "r3",
    title: "Finance Approval Policy FIN-42",
    summary: "Defines executive approval thresholds for budget reallocations and capital commitments.",
    owner: "Finance Operations",
    department: "Finance",
    type: "policy",
    confidence: 99,
    importance: 97,
    tags: ["policy", "approval", "finance", "governance"],
    relationships: ["Budget Variance Memory", "CFO Decision Log", "Approval Timeline"],
    retention: "Permanent",
    updatedAt: "2026-07-10T08:09:00Z",
    aiSummary: "Core policy memory linked to multiple executive workflows and decision nodes.",
    permissions: "Finance, Governance, Legal",
  },
  {
    id: "r4",
    title: "Sales Forecast Delta v12",
    summary: "Forecast drift from pipeline conversion changes in North America and EMEA segments.",
    owner: "Sales Ops",
    department: "Sales",
    type: "workflow",
    confidence: 91,
    importance: 92,
    tags: ["forecast", "sales", "pipeline", "delta"],
    relationships: ["Sales Pipeline", "Forecast Meeting", "QBR Deck"],
    retention: "18 months",
    updatedAt: "2026-07-10T08:25:00Z",
    aiSummary: "Useful for recurring pipeline review and executive forecasting workflows.",
    permissions: "Sales, Finance, Executive",
  },
  {
    id: "r5",
    title: "Workflow Builder Release Note",
    summary: "Captured the v1.2 orchestration pattern for simulation, approvals and policy validation.",
    owner: "Platform Operations",
    department: "Operations",
    type: "workflow",
    confidence: 96,
    importance: 88,
    tags: ["workflow", "release", "simulation"],
    relationships: ["Workflow Builder", "Runtime Events", "Policy Validation"],
    retention: "24 months",
    updatedAt: "2026-07-10T08:33:00Z",
    aiSummary: "Useful for reproducible execution and platform memory lineage.",
    permissions: "Operations, Platform, Executive",
  },
  {
    id: "r6",
    title: "SharePoint Knowledge Sync",
    summary: "Current policy and executive playbooks synchronized with knowledge sources.",
    owner: "Knowledge Curator",
    department: "Engineering",
    type: "knowledge",
    confidence: 93,
    importance: 90,
    tags: ["knowledge", "sync", "sharepoint"],
    relationships: ["Knowledge Graph", "Policy Library", "Memory Collections"],
    retention: "12 months",
    updatedAt: "2026-07-10T06:48:00Z",
    aiSummary: "Knowledge source link ensures memory references resolve to governed content.",
    permissions: "Knowledge, Executive, Governance",
  },
  {
    id: "r7",
    title: "Agent Collaboration Summary",
    summary: "Executive Assistant delegated briefing assembly to Finance Agent and Knowledge Curator.",
    owner: "Executive Assistant",
    department: "Executive",
    type: "agent",
    confidence: 95,
    importance: 89,
    tags: ["agent", "delegation", "briefing"],
    relationships: ["Executive Assistant", "Finance Agent", "Knowledge Curator"],
    retention: "Permanent",
    updatedAt: "2026-07-10T08:39:00Z",
    aiSummary: "Useful for retracing human-AI collaboration and delegation patterns.",
    permissions: "Executive, Agents, Governance",
  },
  {
    id: "r8",
    title: "Decision Log: GDPR Workflow Approval",
    summary: "Human approval granted after policy validation and compliance review.",
    owner: "Compliance Officer",
    department: "Legal",
    type: "decision",
    confidence: 98,
    importance: 96,
    tags: ["decision", "gdpr", "approval", "compliance"],
    relationships: ["GDPR Workflow", "Policy Matrix", "Compliance Council"],
    retention: "Permanent",
    updatedAt: "2026-07-10T08:12:00Z",
    aiSummary: "Critical memory for governance traceability and future audit readiness.",
    permissions: "Legal, Governance, Executive",
  },
];

export const memoryFilters: MemoryFilter[] = [
  { id: "f1", label: "Department" },
  { id: "f2", label: "Team" },
  { id: "f3", label: "Agent" },
  { id: "f4", label: "Workflow" },
  { id: "f5", label: "Customer" },
  { id: "f6", label: "Project" },
  { id: "f7", label: "Policy" },
  { id: "f8", label: "Date" },
];

export const memoryInsights: MemoryInsight[] = [
  { id: "i1", title: "Duplicate memories detected", detail: "2 similar board notes should be merged." },
  { id: "i2", title: "Meeting summary missing", detail: "Executive leadership meeting lacks a final memory summary." },
  { id: "i3", title: "Sales memory outdated", detail: "North America renewal trend not refreshed in 5 days." },
  { id: "i4", title: "Workflow not linked", detail: "Finance forecast memory is not connected to workflow runtime." },
  { id: "i5", title: "Decision missing context", detail: "Budget approval lacks source evidence links." },
  { id: "i6", title: "Executive memory requires review", detail: "Board narrative memory should be validated before publish." },
  { id: "i7", title: "Knowledge confidence decreasing", detail: "Two policy sources have lower freshness thresholds." },
];

export const memoryTimeline: MemoryTimelineEvent[] = [
  { id: "t1", stage: "Captured", description: "Executive planning session recorded", timestamp: "2026-07-10T08:02:00Z" },
  { id: "t2", stage: "Validated", description: "Finance policy memory approved", timestamp: "2026-07-10T08:08:00Z" },
  { id: "t3", stage: "Enriched", description: "Relationships added to renewal risk memory", timestamp: "2026-07-10T08:14:00Z" },
  { id: "t4", stage: "Referenced", description: "Sales forecast linked by AIOS decision engine", timestamp: "2026-07-10T08:20:00Z" },
  { id: "t5", stage: "Updated", description: "Knowledge sync refreshed policy references", timestamp: "2026-07-10T08:31:00Z" },
  { id: "t6", stage: "Archived", description: "Legacy Q2 planning notes archived", timestamp: "2026-07-10T08:45:00Z" },
  { id: "t7", stage: "Deleted", description: "Expired temporary notes removed under governance policy", timestamp: "2026-07-10T08:59:00Z" },
];

export const memoryGraphNodes: MemoryGraphNode[] = [
  { id: "n1", label: "Executive", category: "People", x: 120, y: 120 },
  { id: "n2", label: "Finance", category: "Departments", x: 320, y: 90 },
  { id: "n3", label: "Sales Plan", category: "Projects", x: 540, y: 130 },
  { id: "n4", label: "Enterprise Customer", category: "Customers", x: 760, y: 88 },
  { id: "n5", label: "Policy Library", category: "Policies", x: 920, y: 180 },
  { id: "n6", label: "Workflow Builder", category: "Workflows", x: 680, y: 240 },
  { id: "n7", label: "AI Agents", category: "Agents", x: 420, y: 250 },
  { id: "n8", label: "Decision Logs", category: "Decisions", x: 980, y: 300 },
  { id: "n9", label: "Board Meeting", category: "Meetings", x: 250, y: 290 },
  { id: "n10", label: "Knowledge Base", category: "Knowledge", x: 1100, y: 110 },
];

export const memoryGraphLinks: MemoryGraphLink[] = [
  { id: "l1", from: "n1", to: "n2", label: "approval" },
  { id: "l2", from: "n2", to: "n3", label: "planning" },
  { id: "l3", from: "n3", to: "n4", label: "customer" },
  { id: "l4", from: "n4", to: "n5", label: "policy" },
  { id: "l5", from: "n5", to: "n6", label: "workflow" },
  { id: "l6", from: "n6", to: "n7", label: "agent" },
  { id: "l7", from: "n7", to: "n8", label: "decision" },
  { id: "l8", from: "n9", to: "n1", label: "meeting" },
  { id: "l9", from: "n10", to: "n5", label: "knowledge" },
];

export const memoryContext: MemoryContextItem[] = [
  { id: "c1", label: "Owner", value: "Chief Executive Officer" },
  { id: "c2", label: "Department", value: "Executive" },
  { id: "c3", label: "Permissions", value: "Executive, Finance, Governance" },
  { id: "c4", label: "Retention", value: "Permanent" },
  { id: "c5", label: "Updated", value: "Today 08:16" },
];

export const savedSearches: SavedSearch[] = [
  { id: "s1", label: "Board decisions last 30 days", query: "board decisions" },
  { id: "s2", label: "Customer renewal risk memory", query: "renewal risk" },
  { id: "s3", label: "Policy memories requiring review", query: "policy review" },
];
