import { MockEnterpriseIntegrationAdapter } from "./base-adapter"
import type { IntegrationAdapterDefinition } from "../types"

const definitions: IntegrationAdapterDefinition[] = [
  {
    id: "microsoft-365",
    name: "Microsoft 365",
    vendor: "Microsoft",
    category: "productivity",
    description: "Connect Outlook, Teams, Calendar, and SharePoint signals into AIOS.",
    logoText: "M365",
    authMethods: ["oauth", "enterprise-sso", "service-account"],
    supportedObjects: ["emails", "meetings", "files", "knowledge"],
    transport: ["webhook", "polling"],
    rateLimitPerMinute: 1200,
    retries: 4,
    queue: "queue.enterprise.microsoft",
    health: "healthy",
    authState: "connected",
    lastSync: "2 min ago",
    synchronizedObjects: 18420,
    errors: 0,
    statusDetail: "Exchange, Teams, and SharePoint ingestion active.",
    linkedModules: ["Runtime Engine", "Memory Layer", "Executive Intelligence Center"],
    mock: true,
  },
  {
    id: "google-workspace",
    name: "Google Workspace",
    vendor: "Google",
    category: "productivity",
    description: "Ingest Gmail, Calendar, Drive, and Docs activity.",
    logoText: "GW",
    authMethods: ["oauth", "service-account"],
    supportedObjects: ["emails", "meetings", "files", "knowledge"],
    transport: ["webhook", "polling"],
    rateLimitPerMinute: 900,
    retries: 4,
    queue: "queue.enterprise.google",
    health: "warning",
    authState: "connected",
    lastSync: "14 min ago",
    synchronizedObjects: 11290,
    errors: 2,
    statusDetail: "Drive delta cursor lag detected for one business unit.",
    linkedModules: ["Event Processor", "Prompt OS", "Knowledge"],
    mock: true,
  },
  {
    id: "slack",
    name: "Slack",
    vendor: "Slack",
    category: "communication",
    description: "Observe channels, notifications, workflow triggers, and incident coordination.",
    logoText: "SL",
    authMethods: ["oauth", "api-key"],
    supportedObjects: ["emails", "knowledge"],
    transport: ["webhook", "polling"],
    rateLimitPerMinute: 700,
    retries: 5,
    queue: "queue.enterprise.slack",
    health: "healthy",
    authState: "connected",
    lastSync: "just now",
    synchronizedObjects: 8254,
    errors: 0,
    statusDetail: "Conversation and workflow event stream healthy.",
    linkedModules: ["Runtime Engine", "Workflow Builder", "Multi-Agent Orchestrator"],
    mock: true,
  },
  {
    id: "hubspot",
    name: "HubSpot",
    vendor: "HubSpot",
    category: "crm",
    description: "Bring contacts, companies, deals, and lifecycle events into AIOS.",
    logoText: "HS",
    authMethods: ["oauth", "api-key"],
    supportedObjects: ["contacts", "companies", "deals"],
    transport: ["webhook", "polling"],
    rateLimitPerMinute: 400,
    retries: 3,
    queue: "queue.enterprise.hubspot",
    health: "healthy",
    authState: "connected",
    lastSync: "5 min ago",
    synchronizedObjects: 6402,
    errors: 0,
    statusDetail: "Revenue pipeline sync and enrichment active.",
    linkedModules: ["Planning Engine", "Executive Intelligence Center", "Memory Layer"],
    mock: true,
  },
  {
    id: "salesforce",
    name: "Salesforce",
    vendor: "Salesforce",
    category: "crm",
    description: "Connect account, opportunity, case, and forecasting signals.",
    logoText: "SF",
    authMethods: ["oauth", "enterprise-sso"],
    supportedObjects: ["contacts", "companies", "deals", "tickets"],
    transport: ["webhook", "polling"],
    rateLimitPerMinute: 500,
    retries: 5,
    queue: "queue.enterprise.salesforce",
    health: "rate-limited",
    authState: "connected",
    lastSync: "27 min ago",
    synchronizedObjects: 9210,
    errors: 4,
    statusDetail: "Bulk sync throttled by daily API allocation.",
    linkedModules: ["Planning Engine", "Event Replay", "Executive Intelligence Center"],
    mock: true,
  },
  {
    id: "jira",
    name: "Jira",
    vendor: "Atlassian",
    category: "productivity",
    description: "Track engineering delivery, blockers, and release velocity.",
    logoText: "JI",
    authMethods: ["oauth", "api-key"],
    supportedObjects: ["tickets", "knowledge"],
    transport: ["webhook", "polling"],
    rateLimitPerMinute: 300,
    retries: 4,
    queue: "queue.enterprise.jira",
    health: "healthy",
    authState: "connected",
    lastSync: "6 min ago",
    synchronizedObjects: 3510,
    errors: 0,
    statusDetail: "Issue, sprint, and incident streams healthy.",
    linkedModules: ["Workflow Builder", "Planning Engine", "Memory Layer"],
    mock: true,
  },
  {
    id: "confluence",
    name: "Confluence",
    vendor: "Atlassian",
    category: "knowledge",
    description: "Index internal documentation, decisions, and technical knowledge.",
    logoText: "CF",
    authMethods: ["oauth", "api-key"],
    supportedObjects: ["knowledge", "files"],
    transport: ["polling"],
    rateLimitPerMinute: 240,
    retries: 3,
    queue: "queue.enterprise.confluence",
    health: "healthy",
    authState: "connected",
    lastSync: "11 min ago",
    synchronizedObjects: 4184,
    errors: 0,
    statusDetail: "Knowledge graph indexing and ACL mapping active.",
    linkedModules: ["Memory Layer", "Prompt OS", "Executive Intelligence Center"],
    mock: true,
  },
  {
    id: "notion",
    name: "Notion",
    vendor: "Notion",
    category: "knowledge",
    description: "Capture operating docs, project plans, and team memory.",
    logoText: "NO",
    authMethods: ["oauth"],
    supportedObjects: ["knowledge", "files"],
    transport: ["polling"],
    rateLimitPerMinute: 180,
    retries: 3,
    queue: "queue.enterprise.notion",
    health: "auth-required",
    authState: "required",
    lastSync: "never",
    synchronizedObjects: 0,
    errors: 1,
    statusDetail: "Workspace consent pending for enterprise scope.",
    linkedModules: ["Prompt OS", "Memory Layer"],
    mock: true,
  },
  {
    id: "dropbox",
    name: "Dropbox",
    vendor: "Dropbox",
    category: "storage",
    description: "Synchronize contract, asset, and file intelligence into AIOS.",
    logoText: "DB",
    authMethods: ["oauth", "service-account"],
    supportedObjects: ["files", "knowledge"],
    transport: ["polling"],
    rateLimitPerMinute: 220,
    retries: 2,
    queue: "queue.enterprise.dropbox",
    health: "paused",
    authState: "configured",
    lastSync: "3 hrs ago",
    synchronizedObjects: 2340,
    errors: 0,
    statusDetail: "Paused during document classification policy review.",
    linkedModules: ["Memory Layer", "Event Replay"],
    mock: true,
  },
  {
    id: "sharepoint",
    name: "SharePoint",
    vendor: "Microsoft",
    category: "storage",
    description: "Stream structured documents and governance-controlled files.",
    logoText: "SP",
    authMethods: ["oauth", "enterprise-sso", "service-account"],
    supportedObjects: ["files", "knowledge"],
    transport: ["webhook", "polling"],
    rateLimitPerMinute: 750,
    retries: 4,
    queue: "queue.enterprise.sharepoint",
    health: "healthy",
    authState: "connected",
    lastSync: "8 min ago",
    synchronizedObjects: 7521,
    errors: 0,
    statusDetail: "Document lifecycle and policy sync stable.",
    linkedModules: ["Memory Layer", "Event Processor", "Prompt OS"],
    mock: true,
  },
  {
    id: "quickbooks",
    name: "QuickBooks",
    vendor: "Intuit",
    category: "finance",
    description: "Observe invoices, expenses, and finance-side operating signals.",
    logoText: "QB",
    authMethods: ["oauth", "api-key"],
    supportedObjects: ["invoices", "companies"],
    transport: ["polling"],
    rateLimitPerMinute: 120,
    retries: 3,
    queue: "queue.enterprise.quickbooks",
    health: "warning",
    authState: "connected",
    lastSync: "41 min ago",
    synchronizedObjects: 1844,
    errors: 1,
    statusDetail: "Invoice import behind after CFO approval batch.",
    linkedModules: ["Executive Intelligence Center", "Planning Engine"],
    mock: true,
  },
  {
    id: "xero",
    name: "Xero",
    vendor: "Xero",
    category: "finance",
    description: "Bring ledger movements and invoice signals into decision workflows.",
    logoText: "XE",
    authMethods: ["oauth"],
    supportedObjects: ["invoices", "companies"],
    transport: ["polling"],
    rateLimitPerMinute: 100,
    retries: 3,
    queue: "queue.enterprise.xero",
    health: "offline",
    authState: "configured",
    lastSync: "yesterday",
    synchronizedObjects: 990,
    errors: 3,
    statusDetail: "Sandbox endpoint unavailable for tenant region.",
    linkedModules: ["Event Replay", "Executive Intelligence Center"],
    mock: true,
  },
  {
    id: "zendesk",
    name: "Zendesk",
    vendor: "Zendesk",
    category: "support",
    description: "Ingest customer support flows, queues, and service escalations.",
    logoText: "ZD",
    authMethods: ["oauth", "api-key"],
    supportedObjects: ["tickets", "companies"],
    transport: ["webhook", "polling"],
    rateLimitPerMinute: 250,
    retries: 4,
    queue: "queue.enterprise.zendesk",
    health: "healthy",
    authState: "connected",
    lastSync: "9 min ago",
    synchronizedObjects: 2760,
    errors: 0,
    statusDetail: "Ticket enrichment and urgency scoring active.",
    linkedModules: ["Workflow Builder", "Multi-Agent Orchestrator"],
    mock: true,
  },
  {
    id: "stripe",
    name: "Stripe",
    vendor: "Stripe",
    category: "finance",
    description: "Capture billing, subscription, and payment exception signals.",
    logoText: "ST",
    authMethods: ["api-key", "service-account"],
    supportedObjects: ["invoices", "companies"],
    transport: ["webhook"],
    rateLimitPerMinute: 450,
    retries: 5,
    queue: "queue.enterprise.stripe",
    health: "healthy",
    authState: "connected",
    lastSync: "3 min ago",
    synchronizedObjects: 5820,
    errors: 0,
    statusDetail: "Payment, dispute, and revenue signals flowing.",
    linkedModules: ["Executive Intelligence Center", "Event Processor", "Planning Engine"],
    mock: true,
  },
  {
    id: "shopify",
    name: "Shopify",
    vendor: "Shopify",
    category: "marketing",
    description: "Connect commerce orders, catalog changes, and campaign effects.",
    logoText: "SH",
    authMethods: ["oauth", "api-key"],
    supportedObjects: ["companies", "invoices", "files"],
    transport: ["webhook", "polling"],
    rateLimitPerMinute: 280,
    retries: 4,
    queue: "queue.enterprise.shopify",
    health: "healthy",
    authState: "connected",
    lastSync: "12 min ago",
    synchronizedObjects: 3190,
    errors: 0,
    statusDetail: "Order and conversion events mapped to AIOS business signals.",
    linkedModules: ["Executive Intelligence Center", "Memory Layer", "Workflow Builder"],
    mock: true,
  },
]

export const mockIntegrationAdapters = definitions.map((definition) => new MockEnterpriseIntegrationAdapter(definition))