import type { WorkspaceItem, WorkspaceKey } from "@/types"

export const workspaceItems: WorkspaceItem[] = [
  { key: "home", title: "Home", href: "/app", shortcut: "G H", icon: "home" },
  { key: "executive", title: "Executive", href: "/app/executive", shortcut: "G E", icon: "executive" },
  { key: "corporate", title: "Corporate", href: "/app/corporate", shortcut: "G C", icon: "corporate" },
  { key: "blueprint", title: "Business Blueprint", href: "/app/blueprint", shortcut: "G B", icon: "blueprint" },
  { key: "qbi", title: "QBI", href: "/app/qbi", shortcut: "G Q", icon: "qbi" },
  { key: "sales-intelligence", title: "Sales Intelligence", href: "/app/sales-intelligence", shortcut: "G S", icon: "sales-intelligence" },
  { key: "finance-intelligence", title: "Finance Intelligence", href: "/app/finance-intelligence", shortcut: "G F", icon: "finance-intelligence" },
  { key: "operations", title: "Operations", href: "/app/operations", shortcut: "G O", icon: "operations" },
  { key: "hr", title: "HR", href: "/app/hr", shortcut: "G H R", icon: "hr" },
  { key: "customer-intelligence", title: "Customer Intelligence", href: "/app/customer-intelligence", shortcut: "G U", icon: "customer-intelligence" },
  { key: "knowledge", title: "Knowledge", href: "/app/knowledge", shortcut: "G K", icon: "knowledge" },
  { key: "memory", title: "Memory", href: "/app/memory", shortcut: "G M", icon: "memory" },
  { key: "agents", title: "Agents", href: "/app/agents", shortcut: "G A", icon: "agents" },
  { key: "governance", title: "Governance", href: "/app/governance", shortcut: "G V", icon: "governance" },
  { key: "decisions", title: "Decisions", href: "/app/decisions", shortcut: "G D", icon: "decisions" },
  { key: "integrations", title: "Integrations", href: "/app/integrations", shortcut: "G N", icon: "integrations" },
  { key: "prompt-os", title: "Prompt OS", href: "/app/prompt-os", shortcut: "G P", icon: "prompt" },
  { key: "workflows", title: "Workflows", href: "/app/workflows", shortcut: "G W", icon: "workflow" },
  { key: "orchestrator", title: "Orchestrator", href: "/app/orchestrator", shortcut: "G O", icon: "orchestrator" },
  { key: "planning", title: "Planning", href: "/app/planning", shortcut: "G L", icon: "planning" },
  { key: "insights", title: "Insights", href: "/app/insights", shortcut: "G I", icon: "insights" },
  { key: "reports", title: "Reports", href: "/app/reports", shortcut: "G R", icon: "reports" },
  { key: "mcp", title: "MCP Platform", href: "/app/mcp", shortcut: "G X", icon: "mcp" },
  { key: "security", title: "Security", href: "/app/security", shortcut: "G Y", icon: "security" },
  { key: "settings", title: "Settings", href: "/app/settings", shortcut: "G ,", icon: "settings" },
  { key: "organizations", title: "Organizations", href: "/app/organizations", shortcut: "S O", icon: "organizations", status: "active" },
  { key: "users", title: "Users", href: "/app/users", shortcut: "S U", icon: "users", status: "active" },
  { key: "teams", title: "Teams", href: "/app/teams", shortcut: "S T", icon: "teams", status: "active" },
  { key: "roles", title: "Roles", href: "/app/roles", shortcut: "S R", icon: "roles", status: "active" },
  { key: "permissions", title: "Permissions", href: "/app/permissions", shortcut: "S P", icon: "permissions", status: "active" },
  { key: "audit", title: "Audit", href: "/app/audit", shortcut: "S A", icon: "audit", status: "active" },
  { key: "api-keys", title: "API Keys", href: "/app/api-keys", shortcut: "S K", icon: "api-keys", status: "active" },
  { key: "runtime-center", title: "Runtime Center", href: "/app/runtime-center", shortcut: "R C", icon: "runtime-center", status: "future", badgeLabel: "Roadmap" },
  { key: "developer-center", title: "Developer Center", href: "/app/developer-center", shortcut: "D C", icon: "developer-center", status: "future", badgeLabel: "Roadmap" },
  { key: "mcp-registry", title: "MCP Registry", href: "/app/mcp/registry", shortcut: "M R", icon: "mcp-registry", status: "future", badgeLabel: "Roadmap" },
  { key: "mcp-tools", title: "MCP Tools", href: "/app/mcp/tools", shortcut: "M T", icon: "mcp-tools", status: "future", badgeLabel: "Roadmap" },
  { key: "mcp-resources", title: "MCP Resources", href: "/app/mcp/resources", shortcut: "M S", icon: "mcp-resources", status: "future", badgeLabel: "Roadmap" },
  { key: "mcp-prompts", title: "MCP Prompts", href: "/app/mcp/prompts", shortcut: "M P", icon: "mcp-prompts", status: "future", badgeLabel: "Roadmap" },
  { key: "mcp-health", title: "MCP Health", href: "/app/mcp/health", shortcut: "M H", icon: "mcp-health", status: "future", badgeLabel: "Roadmap" },
  { key: "mcp-gateway", title: "MCP Gateway", href: "/app/mcp/gateway", shortcut: "M G", icon: "mcp-gateway", status: "future", badgeLabel: "Roadmap" },
]

export function getWorkspaceByKey(key: WorkspaceKey): WorkspaceItem | undefined {
  return workspaceItems.find((item) => item.key === key)
}
