import type { BusinessFunctionRole, RoleIntelligenceProfile } from "@/types"

export const roleIntelligenceProfiles: Record<BusinessFunctionRole, RoleIntelligenceProfile> = {
  CEO: {
    id: "CEO",
    focusAreas: ["company performance", "growth", "revenue", "strategic risks"],
    dashboardPriorities: ["executive-summary", "kpi-grid", "risk-dashboard"],
    alertPreferences: ["board-impact", "material-risk", "revenue-swing"],
    recommendationThemes: ["capital-allocation", "strategy", "organization-design"],
    insightBias: ["outcome-overview", "cross-functional-dependency"],
    agentSuggestions: ["Executive Analyst", "Board Briefing Agent"],
    priorityQueues: ["executive-decisions", "enterprise-risks"],
    homeScreenModules: ["executive-workspace", "decision-center", "insights"],
    commandPaletteHints: ["Summarize board risk", "Show growth blockers"],
  },
  "Sales Director": {
    id: "Sales Director",
    focusAreas: ["pipeline", "forecast", "high-value opportunities", "sales coaching"],
    dashboardPriorities: ["sales", "forecast", "opportunity-feed"],
    alertPreferences: ["pipeline-regression", "deal-risk", "quota-gap"],
    recommendationThemes: ["deal-acceleration", "territory-prioritization"],
    insightBias: ["funnel-conversion", "revenue-momentum"],
    agentSuggestions: ["Pipeline Agent", "Revenue Agent"],
    priorityQueues: ["at-risk-deals", "manager-coaching"],
    homeScreenModules: ["sales", "insights", "agents"],
    commandPaletteHints: ["Show at-risk deals", "Generate forecast summary"],
  },
  "Customer Success": {
    id: "Customer Success",
    focusAreas: ["renewals", "churn", "customer health"],
    dashboardPriorities: ["customer-health", "renewal-pipeline"],
    alertPreferences: ["renewal-risk", "sentiment-drop"],
    recommendationThemes: ["retention-playbooks", "expansion-opportunities"],
    insightBias: ["cohort-risk", "usage-adoption"],
    agentSuggestions: ["Retention Agent", "Renewal Agent"],
    priorityQueues: ["next-30-day-renewals", "escalations"],
    homeScreenModules: ["customers", "insights", "workflows"],
    commandPaletteHints: ["Summarize churn drivers", "Prioritize renewals"],
  },
  Finance: {
    id: "Finance",
    focusAreas: ["cash flow", "budgets", "approvals"],
    dashboardPriorities: ["finance", "approvals", "risk-dashboard"],
    alertPreferences: ["cash-threshold", "budget-breach"],
    recommendationThemes: ["spend-control", "scenario-planning"],
    insightBias: ["variance-analysis", "runway"],
    agentSuggestions: ["Finance Review Agent", "Approval Agent"],
    priorityQueues: ["pending-approvals", "budget-anomalies"],
    homeScreenModules: ["decision-center", "reports", "governance"],
    commandPaletteHints: ["Show burn rate", "Review approval backlog"],
  },
  Marketing: {
    id: "Marketing",
    focusAreas: ["campaigns", "content", "lead generation"],
    dashboardPriorities: ["campaign-performance", "lead-quality"],
    alertPreferences: ["campaign-drop", "channel-fatigue"],
    recommendationThemes: ["creative-optimization", "channel-mix"],
    insightBias: ["attribution", "conversion-efficiency"],
    agentSuggestions: ["Campaign Agent", "Content Agent"],
    priorityQueues: ["campaign-anomalies", "content-gaps"],
    homeScreenModules: ["insights", "agents", "planning"],
    commandPaletteHints: ["Find high-performing channels", "Summarize campaign ROI"],
  },
  Operations: {
    id: "Operations",
    focusAreas: ["processes", "automation", "efficiency"],
    dashboardPriorities: ["workflow-throughput", "automation-health"],
    alertPreferences: ["sla-risk", "queue-buildup"],
    recommendationThemes: ["bottleneck-removal", "workflow-tuning"],
    insightBias: ["cycle-time", "handoff-friction"],
    agentSuggestions: ["Operations Agent", "Workflow Optimizer"],
    priorityQueues: ["failing-workflows", "automation-candidates"],
    homeScreenModules: ["workflows", "orchestrator", "runtime"],
    commandPaletteHints: ["Diagnose queue bottlenecks", "Suggest automation opportunities"],
  },
  HR: {
    id: "HR",
    focusAreas: ["hiring", "people", "performance", "training"],
    dashboardPriorities: ["people-health", "hiring-pipeline"],
    alertPreferences: ["attrition-risk", "capacity-gap"],
    recommendationThemes: ["talent-allocation", "development-plans"],
    insightBias: ["retention-patterns", "team-capacity"],
    agentSuggestions: ["People Ops Agent", "Hiring Agent"],
    priorityQueues: ["open-roles", "performance-followups"],
    homeScreenModules: ["organization", "insights", "planning"],
    commandPaletteHints: ["Show hiring bottlenecks", "Summarize retention risks"],
  },
}
