import type {
  KnowledgeCollaborationItem,
  KnowledgeConstellationData,
  KnowledgeContextItem,
  KnowledgeDomain,
  KnowledgeFilter,
  KnowledgeGovernanceItem,
  KnowledgeInsight,
  KnowledgeLifecycleEvent,
  KnowledgeMetric,
  KnowledgeRecord,
  KnowledgeRibbonMetric,
  KnowledgeSavedSearch,
} from "./types";

export const knowledgeMetrics: KnowledgeMetric[] = [
  { id: "k1", label: "Knowledge Assets", value: "18,420", detail: "Governed documents and records", trend: "+4.8%", tone: "success" },
  { id: "k2", label: "Knowledge Health", value: "96%", detail: "Validated and current sources", trend: "+1.1%", tone: "success" },
  { id: "k3", label: "Knowledge Coverage", value: "94%", detail: "Enterprise areas mapped", trend: "+2.4%", tone: "success" },
  { id: "k4", label: "AI Readiness", value: "92%", detail: "Retrieval-ready knowledge", trend: "+3.2%", tone: "success" },
  { id: "k5", label: "Governance Score", value: "97", detail: "Policy and ownership quality", trend: "+1.0", tone: "success" },
  { id: "k6", label: "Policy Compliance", value: "99.1%", detail: "Aligned with approved policy", trend: "+0.4%", tone: "success" },
  { id: "k7", label: "Knowledge Relationships", value: "42,860", detail: "Graph-linked dependencies", trend: "+5.6%", tone: "default" },
  { id: "k8", label: "Knowledge Growth", value: "+1,284", detail: "New items this quarter", trend: "+13.2%", tone: "success" },
  { id: "k9", label: "Knowledge Confidence", value: "95%", detail: "AI verified confidence", trend: "+0.9%", tone: "success" },
  { id: "k10", label: "Linked Memories", value: "12,480", detail: "Memory objects connected", trend: "+6.4%", tone: "success" },
];

export const governanceRibbon: KnowledgeRibbonMetric[] = [
  { id: "r1", label: "AI Readiness", value: "92%", status: "Retrieval-ready", trend: "+2.2%", tone: "success" },
  { id: "r2", label: "Governance Score", value: "97", status: "Strong ownership", trend: "+1", tone: "success" },
  { id: "r3", label: "Policy Compliance", value: "99.1%", status: "All core policies active", trend: "+0.4%", tone: "success" },
  { id: "r4", label: "Review Queue", value: "18", status: "Pending review", trend: "-2", tone: "warning" },
  { id: "r5", label: "Pending Approvals", value: "6", status: "Executive sign-off required", trend: "-1", tone: "warning" },
  { id: "r6", label: "Outdated Knowledge", value: "14", status: "Refresh required", trend: "-3", tone: "critical" },
  { id: "r7", label: "Orphan Knowledge", value: "7", status: "Unlinked assets", trend: "-2", tone: "critical" },
  { id: "r8", label: "Knowledge Health", value: "96%", status: "Operational", trend: "+1.1%", tone: "success" },
];

export const knowledgeDomains: KnowledgeDomain[] = [
  { id: "d1", title: "Executive Strategy", detail: "North-star operating principles and board narrative", documents: 184, owner: "Chief of Staff", status: "Approved", tags: ["board", "strategy", "governance"] },
  { id: "d2", title: "Finance", detail: "Controls, approvals, and forecasting policy", documents: 162, owner: "Finance Operations", status: "Published", tags: ["controls", "forecast", "policy"] },
  { id: "d3", title: "Sales", detail: "Methodology, playbooks, and pipeline standards", documents: 147, owner: "Revenue Operations", status: "Published", tags: ["sales", "playbook", "pipeline"] },
  { id: "d4", title: "Marketing", detail: "Messaging, launches, and campaign standards", documents: 128, owner: "Marketing Ops", status: "Review", tags: ["launch", "content", "brand"] },
  { id: "d5", title: "Operations", detail: "Operational procedures and service workflows", documents: 201, owner: "Operations Excellence", status: "Approved", tags: ["process", "service", "workflow"] },
  { id: "d6", title: "Engineering", detail: "Deployment standards, architecture notes, and runbooks", documents: 219, owner: "Platform Engineering", status: "Published", tags: ["architecture", "runbook", "deploy"] },
  { id: "d7", title: "Legal", detail: "Contracts, obligations, and legal review guidance", documents: 93, owner: "Legal Counsel", status: "Approved", tags: ["contracts", "compliance", "risk"] },
  { id: "d8", title: "Compliance", detail: "Policy enforcement and audit-ready evidence", documents: 118, owner: "Compliance Office", status: "Monitoring", tags: ["audit", "policy", "evidence"] },
  { id: "d9", title: "Security", detail: "Security controls, access standards, incident playbooks", documents: 145, owner: "Security Operations", status: "Approved", tags: ["security", "incident", "access"] },
  { id: "d10", title: "Customer Success", detail: "Onboarding, renewal, and escalations guidance", documents: 176, owner: "Customer Success Ops", status: "Published", tags: ["onboarding", "renewal", "customer"] },
  { id: "d11", title: "AI Playbooks", detail: "Reasoning patterns, prompt standards, and operating rules", documents: 88, owner: "AI Systems", status: "Review", tags: ["ai", "reasoning", "prompt"] },
  { id: "d12", title: "Enterprise Standards", detail: "Canonical standards across business functions", documents: 154, owner: "Knowledge Curator", status: "Approved", tags: ["standard", "policy", "reference"] },
];

export const knowledgeFilters: KnowledgeFilter[] = [
  { id: "department", label: "Department" },
  { id: "business-area", label: "Business Area" },
  { id: "knowledge-type", label: "Knowledge Type" },
  { id: "policy", label: "Policy" },
  { id: "standard", label: "Standard" },
  { id: "owner", label: "Owner" },
  { id: "process", label: "Process" },
  { id: "date", label: "Date" },
];

export const knowledgeSavedSearches: KnowledgeSavedSearch[] = [
  { id: "s1", label: "Board policy updates", query: "executive board policy changes" },
  { id: "s2", label: "AI governance frameworks", query: "approved AI governance framework and review cycles" },
  { id: "s3", label: "Customer onboarding standards", query: "customer onboarding standard and related workflows" },
  { id: "s4", label: "Engineering deployment rules", query: "deployment standard with security and compliance links" },
];

export const knowledgeInsights: KnowledgeInsight[] = [
  { id: "i1", title: "Sales policy requires review.", detail: "The current sales methodology references an outdated pricing approval path.", recommendation: "Route to Revenue Operations and Legal for review.", confidence: 95 },
  { id: "i2", title: "Duplicate onboarding procedure detected.", detail: "Two onboarding standards describe the same approval sequence.", recommendation: "Merge into a single canonical standard and deprecate the duplicate.", confidence: 93 },
  { id: "i3", title: "Knowledge missing for AI workflow.", detail: "The AI assistant workflow lacks a governed knowledge reference for escalation logic.", recommendation: "Create a knowledge page for AI escalation and link it to the workflow.", confidence: 91 },
  { id: "i4", title: "Compliance document outdated.", detail: "The vendor compliance policy has not been refreshed since the last audit cycle.", recommendation: "Schedule immediate review before the next procurement approval.", confidence: 96 },
  { id: "i5", title: "Engineering standards awaiting approval.", detail: "Three engineering standards are still in review and block release guidance.", recommendation: "Escalate to the platform owner for sign-off.", confidence: 90 },
  { id: "i6", title: "Knowledge graph contains orphan nodes.", detail: "Seven knowledge records have no policy, workflow, or decision linkage.", recommendation: "Add canonical links or archive unused records.", confidence: 94 },
  { id: "i7", title: "Customer onboarding playbook incomplete.", detail: "The customer success playbook lacks the new contract handoff checklist.", recommendation: "Extend the playbook with legal and finance dependencies.", confidence: 92 },
];

export const knowledgeGovernance: KnowledgeGovernanceItem[] = [
  { id: "g1", label: "Approvals", value: "6 pending", detail: "Executive and legal sign-off" },
  { id: "g2", label: "Review Cycles", value: "18 active", detail: "Monthly and quarterly cycles" },
  { id: "g3", label: "Version History", value: "1,248 versions", detail: "Tracked across all domains" },
  { id: "g4", label: "Business Rules", value: "214 canonical", detail: "Referenced by workflows and agents" },
  { id: "g5", label: "Ownership", value: "97% assigned", detail: "Known owner and backup owner" },
  { id: "g6", label: "Reviewers", value: "42 reviewers", detail: "Domain and executive reviewers" },
  { id: "g7", label: "Compliance Status", value: "99.1% aligned", detail: "Policy coverage verified" },
  { id: "g8", label: "Change Requests", value: "23 open", detail: "Awaiting triage and closure" },
];

export const knowledgeCollaboration: KnowledgeCollaborationItem[] = [
  { id: "c1", label: "Owner", value: "Knowledge Curator", detail: "Final accountability for the selected knowledge object" },
  { id: "c2", label: "Editors", value: "Finance Ops, Legal Counsel", detail: "Authorized editors with change permissions" },
  { id: "c3", label: "Reviewers", value: "Executive Strategy, Compliance Office", detail: "Active reviewer group for governance" },
  { id: "c4", label: "Departments", value: "Finance, Legal, Operations", detail: "Cross-functional participation" },
  { id: "c5", label: "Comments", value: "128 recent notes", detail: "Discussion captured across review cycles" },
  { id: "c6", label: "Approvals", value: "6 pending", detail: "Waiting on decision owners" },
  { id: "c7", label: "Mentions", value: "84 references", detail: "Referenced in workflows and briefs" },
];

export const knowledgeLifecycle: KnowledgeLifecycleEvent[] = [
  { id: "t1", entityId: "n1", timestamp: Date.parse("2026-07-08T09:10:00Z"), type: "created", title: "Draft created", detail: "Executive Operating Principles drafted from board notes." },
  { id: "t2", entityId: "n2", timestamp: Date.parse("2026-07-08T12:30:00Z"), type: "updated", title: "Policy revised", detail: "Enterprise Security Policy updated with access review requirements." },
  { id: "t3", entityId: "n3", timestamp: Date.parse("2026-07-09T08:05:00Z"), type: "connected", title: "Linked to workflows", detail: "Customer Onboarding Standard linked to approval workflows." },
  { id: "t4", entityId: "n4", timestamp: Date.parse("2026-07-09T11:20:00Z"), type: "executed", title: "Referenced by agents", detail: "Sales Methodology referenced by the Command Center." },
  { id: "t5", entityId: "n5", timestamp: Date.parse("2026-07-09T15:45:00Z"), type: "completed", title: "Approval completed", detail: "AI Governance Framework approved for enterprise use." },
  { id: "t6", entityId: "n6", timestamp: Date.parse("2026-07-10T07:18:00Z"), type: "updated", title: "Standard refreshed", detail: "Engineering Deployment Standard aligned with release policy." },
  { id: "t7", entityId: "n7", timestamp: Date.parse("2026-07-10T08:04:00Z"), type: "archived", title: "Procedure superseded", detail: "Incident Response Procedure replaced by the new playbook." },
  { id: "t8", entityId: "n8", timestamp: Date.parse("2026-07-10T08:41:00Z"), type: "archived", title: "Archive policy completed", detail: "Vendor Compliance Policy archived after annual review." },
];

export const knowledgeContext: KnowledgeContextItem[] = [
  { id: "x1", label: "Permissions", value: "Executive, Legal, Compliance" },
  { id: "x2", label: "Compliance", value: "Audit-ready" },
  { id: "x3", label: "Updated", value: "2026-07-10 08:41 UTC" },
  { id: "x4", label: "Linked Workflows", value: "Board Briefing, Renewal Review" },
  { id: "x5", label: "Linked Decisions", value: "Budget Approval, Policy Change" },
];

export const knowledgeRecords: KnowledgeRecord[] = [
  {
    id: "n1",
    title: "Executive Operating Principles",
    description: "Canonical operating principles used in board narratives and executive briefings.",
    executiveSummary: "AIOS treats this as a top-level governing source for executive decision making.",
    aiSummary: "This record anchors board language, decision framing, and executive communications.",
    businessPurpose: "Keeps strategy, language, and decision criteria aligned across the executive team.",
    owner: "Chief of Staff",
    department: "Executive",
    knowledgeType: "framework",
    businessArea: "Strategy",
    status: "approved",
    version: "v4.2",
    confidence: 98,
    aiReadiness: 97,
    updatedAt: "2026-07-10T08:15:00Z",
    policy: "Board governance policy",
    standard: "Executive documentation standard",
    permissions: "Executive, Board, Strategy",
    approvals: "Board Secretary, CEO",
    compliance: "Fully aligned",
    tags: ["board", "strategy", "principles"],
    relationships: ["AI Governance Framework", "Financial Controls", "Budget Approval"],
    linkedMemories: ["Board planning memory", "Executive briefing lineage"],
    linkedWorkflows: ["Board Briefing", "Quarterly Strategy Review"],
    linkedDecisions: ["Budget Approval", "Market Expansion"],
    relatedPolicies: ["Enterprise Security Policy", "Vendor Compliance Policy"],
    relatedStandards: ["Enterprise Standards", "Business Continuity Framework"],
    reviewers: ["CEO", "Chief of Staff"],
    editors: ["Chief of Staff", "Executive Assistant"],
    comments: 42,
    mentions: 88,
  },
  {
    id: "n2",
    title: "Enterprise Security Policy",
    description: "Security policy covering access control, incident handling, and audit expectations.",
    executiveSummary: "Core policy for access, incident readiness, and enterprise protection.",
    aiSummary: "AIOS uses this as the governance source for risk-sensitive knowledge access.",
    businessPurpose: "Ensures enterprise operations remain secure, auditable, and compliant.",
    owner: "Security Operations",
    department: "Compliance",
    knowledgeType: "policy",
    businessArea: "Risk and Security",
    status: "published",
    version: "v7.1",
    confidence: 99,
    aiReadiness: 96,
    updatedAt: "2026-07-09T17:20:00Z",
    policy: "Security governance policy",
    standard: "Access control standard",
    permissions: "Security, Compliance, IT",
    approvals: "Security Director, Legal",
    compliance: "Audit-ready",
    tags: ["security", "access", "audit"],
    relationships: ["Incident Response Procedure", "Business Continuity Framework", "Vendor Compliance Policy"],
    linkedMemories: ["Security review memory", "Audit exception lineage"],
    linkedWorkflows: ["Access Review", "Incident Response"],
    linkedDecisions: ["Access Approval", "Incident Escalation"],
    relatedPolicies: ["Vendor Compliance Policy", "AI Governance Framework"],
    relatedStandards: ["Enterprise Standards", "Engineering Deployment Standard"],
    reviewers: ["Security Director", "Compliance Manager"],
    editors: ["Security Analyst", "IT Operations"],
    comments: 27,
    mentions: 64,
  },
  {
    id: "n3",
    title: "Customer Onboarding Standard",
    description: "Standardized onboarding steps for enterprise customers and implementation teams.",
    executiveSummary: "Defines how customers are activated and handed over across teams.",
    aiSummary: "Important reference for customer success, support, and revenue handoff automation.",
    businessPurpose: "Reduces onboarding friction and improves retention through a canonical process.",
    owner: "Customer Success Ops",
    department: "Customer Success",
    knowledgeType: "standard",
    businessArea: "Customer Lifecycle",
    status: "approved",
    version: "v3.6",
    confidence: 96,
    aiReadiness: 94,
    updatedAt: "2026-07-09T14:55:00Z",
    policy: "Customer handoff policy",
    standard: "Onboarding standard",
    permissions: "Customer Success, Sales, Operations",
    approvals: "VP Customer Success",
    compliance: "Aligned",
    tags: ["onboarding", "customer", "standard"],
    relationships: ["Sales Methodology", "Financial Controls", "Workflow Builder"],
    linkedMemories: ["Customer onboarding memory", "Implementation review notes"],
    linkedWorkflows: ["Customer Onboarding", "Renewal Review"],
    linkedDecisions: ["Implementation Approval", "Risk Escalation"],
    relatedPolicies: ["Enterprise Security Policy", "Vendor Compliance Policy"],
    relatedStandards: ["Enterprise Standards", "Business Continuity Framework"],
    reviewers: ["Customer Success Lead", "Operations Manager"],
    editors: ["Implementation Manager", "Customer Success Ops"],
    comments: 31,
    mentions: 57,
  },
  {
    id: "n4",
    title: "Sales Methodology",
    description: "Approved sales process, qualification rubric, and pipeline governance.",
    executiveSummary: "Guides seller behavior and pipeline quality across the enterprise.",
    aiSummary: "Referenced by revenue agents when assessing deal quality and next actions.",
    businessPurpose: "Creates a shared language for sales execution and forecasting.",
    owner: "Revenue Operations",
    department: "Sales",
    knowledgeType: "playbook",
    businessArea: "Revenue",
    status: "published",
    version: "v5.0",
    confidence: 95,
    aiReadiness: 93,
    updatedAt: "2026-07-08T16:40:00Z",
    policy: "Revenue policy",
    standard: "Sales methodology standard",
    permissions: "Sales, Finance, Revenue Ops",
    approvals: "VP Sales, CFO",
    compliance: "Aligned",
    tags: ["sales", "pipeline", "methodology"],
    relationships: ["Customer Onboarding Standard", "Financial Controls", "Budget Approval"],
    linkedMemories: ["Pipeline review memory", "Forecast discussion"],
    linkedWorkflows: ["Deal Review", "Pipeline Inspection"],
    linkedDecisions: ["Discount Approval", "Renewal Escalation"],
    relatedPolicies: ["Financial Controls", "Enterprise Security Policy"],
    relatedStandards: ["Enterprise Standards", "Customer Onboarding Standard"],
    reviewers: ["Sales Enablement", "Finance Partner"],
    editors: ["RevOps Analyst", "Sales Leader"],
    comments: 58,
    mentions: 112,
  },
  {
    id: "n5",
    title: "AI Governance Framework",
    description: "Operating framework for AI usage, approval paths, and model governance.",
    executiveSummary: "The central source for AI behavior, approvals, and control expectations.",
    aiSummary: "This record defines how AIOS should reason about governed AI usage.",
    businessPurpose: "Protects the business while enabling AI adoption and explainability.",
    owner: "AI Systems",
    department: "Engineering",
    knowledgeType: "framework",
    businessArea: "AI Operations",
    status: "approved",
    version: "v2.8",
    confidence: 97,
    aiReadiness: 98,
    updatedAt: "2026-07-10T07:55:00Z",
    policy: "AI governance policy",
    standard: "Model usage standard",
    permissions: "AI Systems, Security, Compliance",
    approvals: "AI Steering Committee",
    compliance: "Audit-ready",
    tags: ["ai", "governance", "risk"],
    relationships: ["Enterprise Security Policy", "Engineering Deployment Standard", "Knowledge Graph"],
    linkedMemories: ["AI governance review", "Model approval memory"],
    linkedWorkflows: ["Model Approval", "Policy Review"],
    linkedDecisions: ["Model Approval", "Exception Review"],
    relatedPolicies: ["Enterprise Security Policy", "Vendor Compliance Policy"],
    relatedStandards: ["Enterprise Standards", "Engineering Deployment Standard"],
    reviewers: ["AI Steering Committee", "Security Director"],
    editors: ["AI Systems Lead", "Governance Analyst"],
    comments: 24,
    mentions: 76,
  },
  {
    id: "n6",
    title: "Engineering Deployment Standard",
    description: "Deployment rules for release quality, approvals, rollback, and observability.",
    executiveSummary: "Defines the release path for engineering changes into production.",
    aiSummary: "Referenced when AIOS reasons about deployment risk and release readiness.",
    businessPurpose: "Standardizes engineering releases and protects service stability.",
    owner: "Platform Engineering",
    department: "Engineering",
    knowledgeType: "standard",
    businessArea: "Delivery",
    status: "published",
    version: "v8.4",
    confidence: 94,
    aiReadiness: 92,
    updatedAt: "2026-07-10T06:45:00Z",
    policy: "Delivery governance policy",
    standard: "Release standard",
    permissions: "Engineering, Security, Operations",
    approvals: "Platform Lead",
    compliance: "Aligned",
    tags: ["deployment", "release", "engineering"],
    relationships: ["AI Governance Framework", "Incident Response Procedure", "Business Continuity Framework"],
    linkedMemories: ["Release review memory", "Deployment checklist memory"],
    linkedWorkflows: ["Release Approval", "Change Management"],
    linkedDecisions: ["Go / No-Go", "Rollback Decision"],
    relatedPolicies: ["Enterprise Security Policy", "Financial Controls"],
    relatedStandards: ["Enterprise Standards", "Business Continuity Framework"],
    reviewers: ["Platform Engineer", "Security Reviewer"],
    editors: ["Release Manager", "Platform Engineering"],
    comments: 39,
    mentions: 67,
  },
  {
    id: "n7",
    title: "Incident Response Procedure",
    description: "Operational incident response steps, communication paths, and recovery checks.",
    executiveSummary: "Critical procedure for rapid coordination during service incidents.",
    aiSummary: "The enterprise response playbook for high-severity operational events.",
    businessPurpose: "Minimizes downtime and improves incident communication quality.",
    owner: "Operations Excellence",
    department: "Operations",
    knowledgeType: "procedure",
    businessArea: "Service Reliability",
    status: "deprecated",
    version: "v1.9",
    confidence: 88,
    aiReadiness: 86,
    updatedAt: "2026-07-07T18:10:00Z",
    policy: "Incident governance policy",
    standard: "Response standard",
    permissions: "Operations, Security, Engineering",
    approvals: "Incident Commander",
    compliance: "Needs refresh",
    tags: ["incident", "response", "ops"],
    relationships: ["Enterprise Security Policy", "Engineering Deployment Standard", "Business Continuity Framework"],
    linkedMemories: ["Incident review memory", "RCA note"],
    linkedWorkflows: ["Incident Triage", "Escalation Review"],
    linkedDecisions: ["Emergency Change", "Executive Escalation"],
    relatedPolicies: ["Enterprise Security Policy", "Vendor Compliance Policy"],
    relatedStandards: ["Enterprise Standards", "Business Continuity Framework"],
    reviewers: ["Operations Lead", "Security Manager"],
    editors: ["Incident Manager", "Operations Analyst"],
    comments: 12,
    mentions: 33,
  },
  {
    id: "n8",
    title: "Vendor Compliance Policy",
    description: "Supplier compliance expectations, onboarding controls, and evidence requirements.",
    executiveSummary: "Controls vendor risk and governance across procurement processes.",
    aiSummary: "Used to assess third-party compliance before approvals are finalized.",
    businessPurpose: "Protects the company from supplier and procurement risk.",
    owner: "Legal Counsel",
    department: "Legal",
    knowledgeType: "policy",
    businessArea: "Procurement",
    status: "archived",
    version: "v4.0",
    confidence: 89,
    aiReadiness: 84,
    updatedAt: "2026-07-06T10:00:00Z",
    policy: "Vendor governance policy",
    standard: "Supplier compliance standard",
    permissions: "Legal, Procurement, Compliance",
    approvals: "General Counsel",
    compliance: "Archived after annual review",
    tags: ["vendor", "compliance", "procurement"],
    relationships: ["Financial Controls", "Enterprise Security Policy", "Business Continuity Framework"],
    linkedMemories: ["Procurement review memory", "Vendor risk memory"],
    linkedWorkflows: ["Vendor Review", "Procurement Approval"],
    linkedDecisions: ["Vendor Approval", "Risk Hold"],
    relatedPolicies: ["Enterprise Security Policy", "AI Governance Framework"],
    relatedStandards: ["Enterprise Standards", "Financial Controls"],
    reviewers: ["Legal Counsel", "Procurement Lead"],
    editors: ["Procurement Analyst", "Legal Operations"],
    comments: 18,
    mentions: 21,
  },
  {
    id: "n9",
    title: "Financial Controls",
    description: "Approval limits, controls, and compliance rules for financial operations.",
    executiveSummary: "Defines the guardrails used for spend, approvals, and exception handling.",
    aiSummary: "Referenced by finance and executive workflows for approval decisions.",
    businessPurpose: "Maintains financial discipline and approval traceability.",
    owner: "Finance Operations",
    department: "Finance",
    knowledgeType: "rule",
    businessArea: "Controls",
    status: "approved",
    version: "v6.5",
    confidence: 98,
    aiReadiness: 96,
    updatedAt: "2026-07-10T09:02:00Z",
    policy: "Finance governance policy",
    standard: "Approval controls standard",
    permissions: "Finance, Executive, Audit",
    approvals: "CFO",
    compliance: "Aligned",
    tags: ["finance", "controls", "approval"],
    relationships: ["Sales Methodology", "Executive Operating Principles", "Vendor Compliance Policy"],
    linkedMemories: ["Approval lineage memory", "Forecast control memory"],
    linkedWorkflows: ["Spend Approval", "Budget Review"],
    linkedDecisions: ["Budget Approval", "Spend Exception"],
    relatedPolicies: ["Enterprise Security Policy", "Vendor Compliance Policy"],
    relatedStandards: ["Enterprise Standards", "Business Continuity Framework"],
    reviewers: ["CFO", "Finance Controller"],
    editors: ["Finance Analyst", "Controller"],
    comments: 25,
    mentions: 62,
  },
  {
    id: "n10",
    title: "Business Continuity Framework",
    description: "Recovery, resilience, and continuity guidance for critical business operations.",
    executiveSummary: "Ensures AIOS can explain continuity obligations and recovery expectations.",
    aiSummary: "Critical framework for operational resilience and policy alignment.",
    businessPurpose: "Preserves core operations during disruption or incident conditions.",
    owner: "Operations Excellence",
    department: "Operations",
    knowledgeType: "framework",
    businessArea: "Resilience",
    status: "published",
    version: "v3.3",
    confidence: 95,
    aiReadiness: 93,
    updatedAt: "2026-07-09T20:12:00Z",
    policy: "Continuity policy",
    standard: "Recovery standard",
    permissions: "Operations, Security, Executive",
    approvals: "COO",
    compliance: "Aligned",
    tags: ["continuity", "resilience", "recovery"],
    relationships: ["Enterprise Security Policy", "Incident Response Procedure", "Engineering Deployment Standard"],
    linkedMemories: ["Continuity drill memory", "Recovery planning memory"],
    linkedWorkflows: ["BCP Drill", "Recovery Review"],
    linkedDecisions: ["Recovery Approval", "Escalation Trigger"],
    relatedPolicies: ["Enterprise Security Policy", "Vendor Compliance Policy"],
    relatedStandards: ["Enterprise Standards", "Engineering Deployment Standard"],
    reviewers: ["COO", "Operations Lead"],
    editors: ["Business Continuity Manager", "Operations Analyst"],
    comments: 29,
    mentions: 45,
  },
  {
    id: "n11",
    title: "AI Knowledge Base Taxonomy",
    description: "Canonical taxonomy for how knowledge objects should be categorized and linked.",
    executiveSummary: "Defines the vocabulary AIOS uses to govern knowledge discovery.",
    aiSummary: "A foundational schema for semantic grouping and retrieval behavior.",
    businessPurpose: "Helps AIOS classify knowledge consistently across the organization.",
    owner: "Knowledge Curator",
    department: "Knowledge",
    knowledgeType: "template",
    businessArea: "Knowledge Operations",
    status: "review",
    version: "v1.4",
    confidence: 91,
    aiReadiness: 90,
    updatedAt: "2026-07-10T07:05:00Z",
    policy: "Knowledge governance policy",
    standard: "Knowledge taxonomy standard",
    permissions: "Knowledge, Executive, Compliance",
    approvals: "Knowledge Council",
    compliance: "Under review",
    tags: ["taxonomy", "knowledge", "metadata"],
    relationships: ["Executive Operating Principles", "Enterprise Standards", "AI Governance Framework"],
    linkedMemories: ["Taxonomy review memory", "Knowledge mapping memory"],
    linkedWorkflows: ["Taxonomy Review", "Knowledge Publishing"],
    linkedDecisions: ["Taxonomy Approval", "Metadata Change"],
    relatedPolicies: ["Enterprise Security Policy", "AI Governance Framework"],
    relatedStandards: ["Enterprise Standards", "Knowledge Management Standard"],
    reviewers: ["Knowledge Council", "Compliance Officer"],
    editors: ["Knowledge Curator", "Metadata Specialist"],
    comments: 17,
    mentions: 54,
  },
  {
    id: "n12",
    title: "Business Rules Catalog",
    description: "Central catalog of business rules used by workflows, decisions, and agents.",
    executiveSummary: "The canonical place for rule-driven operational logic.",
    aiSummary: "AIOS uses this catalog to reason about automated and human-reviewed logic.",
    businessPurpose: "Prevents rule duplication and keeps operational logic explainable.",
    owner: "Business Architecture",
    department: "Operations",
    knowledgeType: "process",
    businessArea: "Rules and Decisions",
    status: "published",
    version: "v2.1",
    confidence: 97,
    aiReadiness: 95,
    updatedAt: "2026-07-10T08:26:00Z",
    policy: "Rules governance policy",
    standard: "Decision standard",
    permissions: "Operations, Product, Engineering",
    approvals: "Business Architecture Lead",
    compliance: "Aligned",
    tags: ["rules", "catalog", "decision"],
    relationships: ["Financial Controls", "AI Governance Framework", "Workflow Builder"],
    linkedMemories: ["Rules maintenance memory", "Decision lineage memory"],
    linkedWorkflows: ["Rule Review", "Decision Mapping"],
    linkedDecisions: ["Policy Exception", "Workflow Authorization"],
    relatedPolicies: ["Enterprise Security Policy", "Vendor Compliance Policy"],
    relatedStandards: ["Enterprise Standards", "AI Knowledge Base Taxonomy"],
    reviewers: ["Business Architect", "Operations Manager"],
    editors: ["Business Analyst", "Process Owner"],
    comments: 33,
    mentions: 71,
  },
];

export const knowledgeConstellation: KnowledgeConstellationData = {
  nodes: [
    { id: "n1", label: "Knowledge Domains", type: "department", department: "knowledge", businessUnit: "Knowledge", owner: "Knowledge Curator", status: "active", priority: "high", confidence: 97, summary: "Primary governed knowledge domains", metadata: { kind: "cluster", layer: "governance" }, x: 180, y: 140, radius: 26 },
    { id: "n2", label: "Policies", type: "policy", department: "knowledge", businessUnit: "Governance", owner: "Compliance Office", status: "active", priority: "high", confidence: 99, summary: "Approved policy layer", metadata: { kind: "cluster", layer: "policy" }, x: 410, y: 100, radius: 24 },
    { id: "n3", label: "Standards", type: "knowledge-document", department: "knowledge", businessUnit: "Governance", owner: "Knowledge Curator", status: "active", priority: "high", confidence: 98, summary: "Canonical standards", metadata: { kind: "cluster", layer: "standards" }, x: 390, y: 290, radius: 24 },
    { id: "n4", label: "Business Rules", type: "goal", department: "operations", businessUnit: "Decisioning", owner: "Business Architecture", status: "active", priority: "high", confidence: 96, summary: "Rules that drive actions", metadata: { kind: "cluster", layer: "rules" }, x: 650, y: 130, radius: 24 },
    { id: "n5", label: "Processes", type: "workflow", department: "operations", businessUnit: "Execution", owner: "Operations Excellence", status: "active", priority: "high", confidence: 95, summary: "Operational procedures and workflows", metadata: { kind: "cluster", layer: "process" }, x: 650, y: 300, radius: 24 },
    { id: "n6", label: "Departments", type: "department", department: "executive", businessUnit: "Enterprise", owner: "Chief of Staff", status: "active", priority: "medium", confidence: 94, summary: "Cross-functional knowledge ownership", metadata: { kind: "cluster", layer: "org" }, x: 890, y: 90, radius: 24 },
    { id: "n7", label: "Products", type: "product", department: "sales", businessUnit: "Commercial", owner: "Product Marketing", status: "active", priority: "medium", confidence: 93, summary: "Product knowledge and positioning", metadata: { kind: "cluster", layer: "commercial" }, x: 890, y: 250, radius: 24 },
    { id: "n8", label: "Projects", type: "project", department: "operations", businessUnit: "Delivery", owner: "PMO", status: "monitoring", priority: "medium", confidence: 92, summary: "Active project knowledge", metadata: { kind: "cluster", layer: "delivery" }, x: 1120, y: 120, radius: 24 },
    { id: "n9", label: "Customers", type: "company", department: "sales", businessUnit: "Commercial", owner: "Customer Success", status: "active", priority: "high", confidence: 95, summary: "Customer-facing knowledge nodes", metadata: { kind: "cluster", layer: "customer" }, x: 1120, y: 300, radius: 24 },
    { id: "n10", label: "AI Agents", type: "agent", department: "platform", businessUnit: "AI Systems", owner: "AI Systems", status: "active", priority: "critical", confidence: 98, summary: "Knowledge-aware agents", metadata: { kind: "cluster", layer: "ai" }, x: 1370, y: 150, radius: 24 },
    { id: "n11", label: "Memory Collections", type: "memory-node", department: "knowledge", businessUnit: "Memory", owner: "Knowledge Curator", status: "active", priority: "medium", confidence: 94, summary: "Linked living memory", metadata: { kind: "cluster", layer: "memory" }, x: 1370, y: 300, radius: 24 },
    { id: "n12", label: "Decisions", type: "goal", department: "executive", businessUnit: "Decisioning", owner: "Executive Team", status: "active", priority: "high", confidence: 96, summary: "Decision lineage and approval context", metadata: { kind: "cluster", layer: "decision" }, x: 1600, y: 190, radius: 24 },
    { id: "n13", label: "Requirements", type: "task", department: "platform", businessUnit: "Delivery", owner: "Product Operations", status: "monitoring", priority: "medium", confidence: 91, summary: "Linked requirements and scope notes", metadata: { kind: "cluster", layer: "requirements" }, x: 1600, y: 340, radius: 24 },
  ],
  edges: [
    { id: "e1", source: "n1", target: "n2", label: "governs", strength: 92, category: "dependency", animated: true },
    { id: "e2", source: "n1", target: "n3", label: "organizes", strength: 88, category: "direct", animated: true },
    { id: "e3", source: "n1", target: "n4", label: "defines", strength: 90, category: "knowledge-dependency", animated: true },
    { id: "e4", source: "n3", target: "n5", label: "supports", strength: 86, category: "workflow-dependency", animated: true },
    { id: "e5", source: "n4", target: "n6", label: "aligned to", strength: 84, category: "decision-influence", animated: true },
    { id: "e6", source: "n5", target: "n7", label: "enables", strength: 78, category: "workflow-dependency", animated: true },
    { id: "e7", source: "n5", target: "n8", label: "tracks", strength: 81, category: "direct", animated: true },
    { id: "e8", source: "n6", target: "n9", label: "serves", strength: 76, category: "indirect", animated: true },
    { id: "e9", source: "n7", target: "n10", label: "operates with", strength: 79, category: "knowledge-dependency", animated: true },
    { id: "e10", source: "n2", target: "n11", label: "links", strength: 74, category: "direct", animated: true },
    { id: "e11", source: "n10", target: "n12", label: "recommends", strength: 91, category: "decision-influence", animated: true },
    { id: "e12", source: "n11", target: "n13", label: "feeds", strength: 82, category: "workflow-dependency", animated: true },
    { id: "e13", source: "n12", target: "n13", label: "informs", strength: 80, category: "decision-influence", animated: true },
  ],
};
